### ISSUE TITLE
Change CGIAR by IBP in ontology names

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#10]
Modification à apporter (signalée par Elizabeth) : dans AgroPortal, pour les ontologies dont le
nom comprend CGIAR, remplacer par IBP

**Comment by vemonet** [comment]
Fait :
http://agroportal.lirmm.fr/ontologies/CO_320
http://agroportal.lirmm.fr/ontologies/CO_715
http://agroportal.lirmm.fr/ontologies/CO_121
http://agroportal.lirmm.fr/ontologies/CO_321
