### ISSUE TITLE
Upload GACS

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#101]
Open to follow up on #35.

**Comment by jonquet** [comment]
Ok. Good news @antool @tombaker the file is parsed and  the ontology show up. 
Very quick: 
- all the SKOS-XL labels do not seems to be reported in main skos:Concept so are ignored by AgroPortal
- not sure how language tag are defined... but they are not ignored by AgroPortal indexing
- because of label issues, /annotator do not work yet

To be completed...

**Comment by osma** [comment]
@jonquet Thanks for testing GACS loading! Can you provide concrete examples of the problems in GACS data so I can take a look? It's possible there are problems in the way the GACS data was created in VocBench and/or how it was enriched for publication.

**Comment by antool** [comment]
@osma @tombaker @jonquet 
Loading gacs-beta-4.0 : [GACS](http://agroportal.lirmm.fr/ontologies/GACS)
Displaying 3 top concepts for "Global Agricultural Concept Scheme **Core**" and  6 for "Global Agricultural Concept Scheme **non-core** concepts" (flat hierarchy for the second one).
The prefLabel displayed are the skosXL ones, not the skos:prefLabel ones.
