### ISSUE TITLE
Index only synomyms in the language of the portal

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#104]
We have observed on Agrovoc, GACS that if synonyms are defined in other languages than the one of the portal (e.g., English for AgroPortal, French for SIFR) then they are parsed and indexed in search and annotator. 
This is an issue as the multilingual synonyms end up being mixed with the main languages labels.

Examples:
http://agroportal.lirmm.fr/search?q=agriculture&ontologies=AGROVOC&include_properties=false&include_views=false&includeObsolete=false&require_definition=false&exact_match=false

http://services.agroportal.lirmm.fr/annotator/?text=agriculture%20and%20faaliyet&ontologies=AGROVOC&longest_only=false&exclude_numbers=false&whole_word_only=true&exclude_synonyms=false&expand_mappings=false&negation=false&temporality=false&lemmatize=false&display_links=false&display_context=false

CC @mdorf has this behavior shall be the same on BioPortal.
This is not SKOS specific.

**Comment by vemonet** [comment]
Something has already be done here:
https://github.com/ncbo/goo/blob/master/lib/goo/sparql/queries.rb#L727:L738

But it doesn't seems to work with Synonyms.

And it would be better to define the language as a param in config files (with :en by default)

**Comment by vemonet** [comment]
Example of concept with synonyms from different languages: http://agroportal.lirmm.fr/ontologies/AGROVOC/?p=classes&conceptid=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_7038&jump_to_nav=true

**Comment by vemonet** [comment]
Note that for Agrovoc it is particuliar as it is using skos XL labels

I am doing some tests with 
https://github.com/sifrproject/ontologies_linked_data/blob/sifr_metadata/test/data/ontology_files/agrooeMappings-05-05-2016.owl#L398:L404

Language is well defined for all labels. However, what is retrieved here: https://github.com/ncbo/goo/blob/master/lib/goo/sparql/queries.rb#L727:L738
* prefLabel without the language tags (they disappeared in the process)
* synonyms with the language tags (no altLabel properties, but at least we got the synonyms. And this time the lang tag did not disappear in the process)

Even when I set "prefLabelProperty": "http://www.w3.org/2000/01/rdf-schema#label"" it takes the skos:prefLabel for label


The actual hack to have only eng properties is not working properly with array of value.

**Comment by vemonet** [comment]
Now better handling of languages. https://github.com/sifrproject/goo/commit/172f7867aa9775866eda2ef43f9015f8611971f9

The user can set the main languages used by the Portal in the config files (Goo.main_lang = ["en", "eng", "fr"] for example)

The portal will in priority pick a prefLabel from one of those lang (if not available then it will pick one randomly)
For other properties (like synonyms and definition) only the properties from the main lang (and properties that don't have a defined lang) will be used

**Comment by vemonet** [comment]
Faire le filtre seulement sur l'annotator.
On affiche bien toutes les langues dans les synonyms, etc. Mais quand on annote on aimerait annoter seulement dans une langue. Donc faudrait juste garder seulement les synonymes de la langue voulue quand on créé le dictionnaire

**Comment by vemonet** [comment]
Example working: http://stageportal.lirmm.fr/ontologies/NALT-TEST/?p=classes&conceptid=http%3A%2F%2Flod.nal.usda.gov%2Fnalt%2F5408

"agricultura (general)" : ancienne version ça matchait. Nouvelle (après indexation) ça ne doit plus marcher
Pourtant.
http://data.stageportal.lirmm.fr/search?q=agricultura%20(general)&ontologies=NALT-TEST retourne un résultat avec prefLabel et synonyms totalement différents de ceux définis dans le modèle de données classique... Comment ils font ?
http://data.stageportal.lirmm.fr/ontologies/NALT-TEST/classes/http%3A%2F%2Flod.nal.usda.gov%2Fnalt%2F5260

Vérifier que comportement bon au niveau de l'indexation et de l'annotation

**Comment by vemonet** [comment]
Et que l'indexation est OK avec SKOS

**Comment by vemonet** [comment]
New multilangue indexing works on stage for terms and properties

But indexing error for 2 ontologies : http://stageportal.lirmm.fr/ontologies/AEO/ and http://stageportal.lirmm.fr/ontologies/DBTST

Example: http://data.stageportal.lirmm.fr/search?q=agricultural%20experiment&ontologies=AEO

May be because of lack of "label" attributes for properties : 
```shell
# AEO
INFO -- : ["Starting to process AEO/submissions/1"]
I, [2017-06-20T10:40:32.210593 #8878]  INFO -- : ["Indexing ontology properties: AEO..."]
I, [2017-06-20T10:40:32.216453 #8878]  INFO -- : ["Removed ontology properties index in 0.00568443 seconds."]
I, [2017-06-20T10:40:34.766584 #8878]  INFO -- : ["Indexing a total of 1 pages of 2500 properties each."]
E, [2017-06-20T10:40:34.785140 #8878] ERROR -- : ["Goo::Base::AttributeNotLoaded: Attribute `label` is not loaded for http://purl.org/dc/terms/abstract. Loaded attributes: #<Set: {:parents, :definition, :submission}>.\n/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/goo-025d3f9ef569/lib/goo/base/settings/settings.rb:272:in `block in shape_attribute'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/properties/ontology_property.rb:224:in `get_index_doc'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/properties/annotation_property.rb:25:in `block in <class:AnnotationProperty>'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/goo-025d3f9ef569/lib/goo/search/search.rb:28:in `get_indexable_object'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/goo-025d3f9ef569/lib/goo/search/search.rb:50:in `block in indexBatch'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/goo-025d3f9ef569/lib/goo/search/search.rb:49:in `each'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/goo-025d3f9ef569/lib/goo/search/search.rb:49:in `indexBatch'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/ontology_submission.rb:2072:in `block (2 levels) in index_properties'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/ontology_submission.rb:2070:in `each'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/ontology_submission.rb:2070:in `each_slice'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/ontology_submission.rb:2070:in `block in index_properties'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/ontology_submission.rb:2057:in `index_properties'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/ontology_submission.rb:1766:in `process_submission'\n\t/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:193:in `process_submission'\n\tbin/ncbo_ontology_property_index:96:in `index_ontology_properties'\n\tbin/ncbo_ontology_property_index:156:in `block (2 levels) in <main>'\n\tbin/ncbo_ontology_property_index:155:in `each'\n\tbin/ncbo_ontology_property_index:155:in `block in <main>'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'\n\tbin/ncbo_ontology_property_index:146:in `<main>'"]

# DBTST
I, [2017-06-20T10:38:06.723766 #8878]  INFO -- : ["Removed ontology properties index in 0.007127421 seconds."]
I, [2017-06-20T10:38:10.145061 #8878]  INFO -- : ["Indexing a total of 1 pages of 2500 properties each."]
E, [2017-06-20T10:38:10.177864 #8878] ERROR -- : ["Goo::Base::AttributeNotLoaded: Attribute `label` is not loaded for http://purl.org/dc/elements/1.1/contributor. Loaded attributes: #<Set: {:parents, :definition, :submission}>.\n/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/goo-025d3f9ef569/lib/goo/base/settings/settings.rb:272:in `block in shape_attribute'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/properties/ontology_property.rb:224:in `get_index_doc'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/properties/annotation_property.rb:25:in `block in <class:AnnotationProperty>'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/goo-025d3f9ef569/lib/goo/search/search.rb:28:in `get_indexable_object'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/goo-025d3f9ef569/lib/goo/search/search.rb:50:in `block in indexBatch'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/goo-025d3f9ef569/lib/goo/search/search.rb:49:in `each'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/goo-025d3f9ef569/lib/goo/search/search.rb:49:in `indexBatch'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/ontology_submission.rb:2072:in `block (2 levels) in index_properties'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/ontology_submission.rb:2070:in `each'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/ontology_submission.rb:2070:in `each_slice'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/ontology_submission.rb:2070:in `block in index_properties'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/ontology_submission.rb:2057:in `index_properties'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/ontologies_linked_data-bf28db1a4b3a/lib/ontologies_linked_data/models/ontology_submission.rb:1766:in `process_submission'\n\t/srv/ncbo/ncbo_cron/lib/ncbo_cron/ontology_submission_parser.rb:193:in `process_submission'\n\tbin/ncbo_ontology_property_index:96:in `index_ontology_properties'\n\tbin/ncbo_ontology_property_index:156:in `block (2 levels) in <main>'\n\tbin/ncbo_ontology_property_index:155:in `each'\n\tbin/ncbo_ontology_property_index:155:in `block in <main>'\n\t/usr/local/rbenv/versions/2.3.3/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'\n\tbin/ncbo_ontology_property_index:146:in `<main>'"]
```

**Comment by vemonet** [comment]
Fixed. Warn me if you any bug. It will be in production soon

**Comment by jonquet** [comment]
En attente de test finaux en production.
