### ISSUE TITLE
Feature "Get my metadata back"

### ISSUE THREAD

**Issue by vemonet** [agroportal/agroportal_web_ui#107]
Ajouter dans le summary (à côté du bouton pour accéder au JSON ?) un bouton permettant de télécharger les metadata de l'ontologie au format RDF dans plusieurs syntaxes différentes
Le but étant de pouvoir ensuite copier/coller les metadata dans l'ontologie

La lib suivante peut être utilisée : 
http://json-ld.org/playground/
https://github.com/json-ld/json-ld.org

**Comment by vemonet** [comment]
Sur ontology on récupère toutes les metadata qui sont "N" pour la colonne "Bioportal Specific" dans https://docs.google.com/spreadsheets/d/1r1twxJvXdQXrkX0Ocis6YY08nlO5cGneCAQ5F7U_CoA/edit#gid=0
name, acronym, group, mais pas hasDomain (déjà au niveau de la submission)

**Comment by vemonet** [comment]
Au niveau des metrics : on récupère les 3 omv au niveau de la submission (numberOf: Classes, individuals, properties, axioms). Et le reste dans l'objet metrics

On devrait en avoir 125 en tout

**Comment by vemonet** [comment]
Now @id is taken from ontology ID URI if no URI 
Add metrics, creationDate, released, id, name

**Comment by antool** [comment]
@vemonet 
Est-il possible d'ajouter RDF/XML comme format de sortie ?

**Comment by vemonet** [comment]
C'est fait, bientôt poussé

**Comment by saubin78** [comment]
Super! est-ce que la prochaine release incluera les métadonnées statistiques numberOf: Classes, individuals, properties, axioms ?

**Comment by vemonet** [comment]
Ca a été poussé et j'ai rajouté les metrics

**Comment by vemonet** [comment]
Note: we generate RDF/XML manually (no lib meeting the requirements found)
https://github.com/sifrproject/bioportal_web_ui/blob/sifr_metadata/app/assets/javascripts/bp_ontology_viewer.js.erb#L505
