### ISSUE TITLE
Change the metadata "used Ontology Engineering Tool"

### ISSUE THREAD

**Issue by antool** [agroportal/agroportal_web_ui#109]
J'ai commencé à harmoniser la syntaxe des métadonnées en privilégiant chaque fois que possible les URL ou URI.
Par exemple, pour OBO EDIT, choisir : http://oboedit.org/
1) Mais impossible de modifier ce champ pour certaines ontologies (cela ne marche ni via l'UI, ni avec un CURL), par exemple pour : WHEATPHENOTYPE, CO_020, CO_121, VARIO.
2) Suggestion : ajouter dans la liste des propositions à l'utilisateur "OBO EDIT" et "OWL API" (souvent utilisés)

**Comment by vemonet** [comment]
OboEdit et OWLAPI rajouté.
Est-ce qu'il serait intéressant de changer certaines entrées pour mettre des URIs à la place ( http://protege.stanford.edu par exemple)

**Comment by antool** [comment]
Ce qui serait bien, c'est qu'on ait à l'affichage un bouton cliquable dont le label serait le nom de l'outil ("Protégé" par exemple) qui pointerait sur l'url associée (ici http://protege.stanford.edu/).
Il faudrait appliquer ce principe chaque fois que possible pour nos métadonnées : pour la langue, includedInDataCatalog, etc.

**Comment by antool** [comment]
@vemonet 
Si mes souvenirs sont bons, tu as dû supprimer toutes les valeurs pour cette propriété dans AgroPortal.
Il faut donc les saisir à nouveau mais je ne vois toujours pas ni OboEdit ni OWLAPI dans la liste. Qu'en est-il ?

**Comment by vemonet** [comment]
Je pousse aujourd'hui en production
