### ISSUE TITLE
Assign the most appropriate pull URL propoerty for PO and PTO

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#11]
We are trying to figure out the best pull URL for 
http://agroportal.lirmm.fr/ontologies/PO
http://agroportal.lirmm.fr/ontologies/PTO

The property is called "pullLocation"
http://data.agroportal.lirmm.fr/ontologies/PO/submissions/1?&include=all&display_context=false&display_links=false
http://data.agroportal.lirmm.fr/ontologies/PTO/submissions/1?&include=all&display_context=false&display_links=false

Pierre, est ce que tu conseilles de prendre:
http://purl.obolibrary.org/obo/po.owl (qui nous donne visiblement la meme chose que ce qu'on a deja dans AgroPortal)
http://purl.obolibrary.org/obo/to.owl (qui nous donne visiblement autre chose)

Ou est-ce qu'on doit privilégier:
https://github.com/Planteome/plant-ontology
https://github.com/Planteome/plant-trait-ontology

Visiblement pour PTO, les différents fichiers ne donne pas la même chose et on se retrouve avec 3 ontologies différentes pour PTO:
http://bioportal.bioontology.org/ontologies/PTO/?p=classes&conceptid=root
http://stageportal.lirmm.fr/ontologies/TO/?p=classes (appelle TO juste pour le test)
http://stageportal.lirmm.fr/ontologies/PTO/?p=classes

Pierre tu aurais des éléments ?

**Comment by jonquet** [comment]
A mon avis il faut les prendre ici: http://www.planteome.org/node/1
Et aller directement se connecter a GitHub

**Comment by jonquet** [comment]
Discuter avec Laurel a PAG 2016. Il faut utiliser:

PO:
http://purl.obolibrary.org/obo/po.owl which brings to
https://raw.githubusercontent.com/Planteome/plant-ontology/master/po.owl
TO:
http://purl.obolibrary.org/obo/to.owl which brings to
https://raw.githubusercontent.com/Planteome/plant-trait-ontology/master/to.owl
EO:
http://purl.obolibrary.org/obo/eo.owl which brings to 
http://www.berkeleybop.org/ontologies/eo.owl
but I guess soon to GitHub

Faut donc changer le format de ces ontologies et prendre OWL (qui est le format source) et vérifier que tout ce passe bien.
Voir aussi email avec Laurel pour voir si on met:
PSO (mais vide)
et PDO

**Comment by vemonet** [comment]
EO correspond à PECO, qui est déjà uploadé dans AgroPortal
http://agroportal.lirmm.fr/ontologies/PECO
TO et PO ont été mis à jour sur AgroPortal

**Comment by jonquet** [comment]
Pour PECO, il faut changer le nom en EO et changer la pullLocation a 
http://www.berkeleybop.org/ontologies/eo.owl

Poru le moment on a un cycle dans notre systeme comment c'est possible ? 
"pullLocation": "http://data.agroportal.lirmm.fr/ontologies/PECO/submissions/11/download?apikey=4a5011ea-75fa-4be6-8e89-f45c8c84844e"
On ne devrait jamais donner une pullLocation qui est chez nous !

**Comment by vemonet** [comment]
Il vaudrait pas mieux mettre http://purl.obolibrary.org/obo/eo.owl en pullLocation ? Ca redirige vers http://www.berkeleybop.org/ontologies/eo.owl de toute façon.

**Comment by pierrelarmande** [comment]
Hello, 

a mon avis c ce qu il faudrait faire. 

Pierre

**Comment by antool** [comment]
Vincent a mis à jour les acronymes et les pullLocation pour ces ontologies :
EO : http://purl.obolibrary.org/obo/eo.owl
PO : http://purl.obolibrary.org/obo/po.owl
TO : http://purl.obolibrary.org/obo/to.owl
