### ISSUE TITLE
Mise à jour des métadonnées de certaines ontologies impossible

### ISSUE THREAD

**Issue by antool** [agroportal/agroportal_web_ui#110]
Le problème de mise à jour indiqué dans #109 pour certaines ontologies est vrai pour toutes les métadonnées. Par exemple, impossible de modifier les métadonnées de WHEATPHENOTYPE pour les rendre conformes à la syntaxe indiquée dans #88

**Comment by antool** [comment]
La plateforme est très instable en fait. la mise à jour via l'UI peut rater 10 fois de suite et réussir à la onzième ! Sauf pour agroportal/documentation#110 (toujours d'actualité)

**Comment by jonquet** [comment]
Faut qu'on regarde ca. Il y a eu des changements de code un peu recement (et le merge avec le dernier code d'NCBO a aussi été fait.  Je ne sais pas d'ou cela peut venir.

**Comment by vemonet** [comment]
Les modifications de usedOntologyEngineeringTool ne sont pas correctement enregistrées sur stageportal et agroportal. Même en passant par la console. Pour les autres metadata il n'y a pas de problème mais pour usedOntologyEngineeringTool ça ne veut pas enregistrer

Quand on essaie de debugger en lançant l'API en development évidemment ça marche sans problème...

Test exemple via console sur stageportal :
```ruby
sub.usedOntologyEngineeringTool="new tool"
sub.hasLicense="new license"
sub.save
```
A ce point sub est correctement modifié pour hasLicense et usedOntologyEngineeringTool. Mais si on quitte la console et y retourne alors seulement hasLicense a été enregistré

En fait usedOntologyEngineeringTool est correctement modifié pour certaines ontologies (tel que SIO) mais pas d'autres (tel que EO). Il semble que pour des ontologies où il est déjà défini ça plante.

**Comment by vemonet** [comment]
Pour une raison totalement mystérieuse le problème est que quand on modifie la metadata la nouvelle propriété n'écrase pas l'ancienne. L'ancienne est gardée et la nouvelle est ajoutée à côté...

Et ceci seulement pour les submissions pour lesquelles usedOntologyEngineeringTool a été défini avant (pourtant ce n'est pas écrit dans le 4store ça, il n'y a aucune raison pour rencontrer ce comportement)

**Comment by vemonet** [comment]
Solution possible à tester : supprimer tous les triplets concernant la metadata usedOntologyEngineeringTool
Ou refaire de A à Z toute la plateforme pour que ça soit codé correctement et fonctionnel

**Comment by antool** [comment]
J'ai enfin réussi à mettre à jour les métadonnées de Biorefinery via l'UI.
Impossible en revanche d'accéder à la page " Edit submission information" de Transmat.

**Comment by antool** [comment]
Finalement, le problème de TRANSMAT est réglé. @vemonet a peut-être fait le nécessaire ?

**Comment by vemonet** [comment]
Non, mais je sais d'où ça vient. Je vais régler ça dans la semaine (comme pour la page Summary l'UI essaie de récupérer toutes les submissions au lieu de la dernière)

**Comment by vemonet** [comment]
On avait ce problème pour vann:preferredNamespacePrefix également. J'ai supprimer les triples pour vann:preferredNamespacePrefix et omv:usedOntologyEngineeringTool du coup.
Par contre on ne sait pas exactement pourquoi ils ont été créés avec un datatype String explicit.
Tu me confirmes que c'est bon ? Je vais bientôt pousser la nouvelle UI (avec les choix supplémentaires pour omv:usedOntologyEngineeringTool)

**Comment by vemonet** [comment]
J'ai amélioré la façon de récupérer les infos des submissions pour l'édition des submissions. C'est beaucoup plus rapide pour afficher la page pour éditer les metadata. Et quand on save les metadata c'est un peu plus rapide (mais reste encore relativement lent).

J'ai déjà répertorié ce problème ici : https://github.com/sifrproject/bioportal_web_ui/issues/19

**Comment by vemonet** [comment]
Add and edit a new submission is now way faster (cache problems fixed). See https://github.com/sifrproject/bioportal_web_ui/issues/19 for more details. it has been pushed to AgroPortal
