### ISSUE TITLE
Landscape count of "BioPortal" ontologies is wrong

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#111]
Landscape page currently counts 18 ontologies in BioPortal (in diagram "data catalog") where as we have 26 of the with the metadata field http://bioportal.bioontology.org/ontologies/SOMETHING
I double checked manually.

**Comment by vemonet** [comment]
Assez simple : il y en a 18 avec http://bioportal.bioontology.org/ontologies et 10 avec https://bioportal.bioontology.org/ontologies

**Comment by vemonet** [comment]
Corrigé, et j'ai rajouté également le nombre d'ontologie pour le portal utilisé dans includedInDataCatalog
