### ISSUE TITLE
Chargement de/des vocabulaires de Catherine Roussey (IRSTEA)

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#12]
Problème d'affichage des vocabulaires proposés par Catherine R.
Hypothèse : mauvaise prise en charge par le portail

**Comment by jonquet** [comment]
Est-ce qu'on peut avoir l'URL dans stage?

**Comment by antool** [comment]
Les problèmes d'affichage sont résolus. Le vocabulaire sera chargé lorsque Catherine aura produit une version plus avancée.

**Comment by antool** [comment]
En attente d'une nouvelle version du vocabulaire de Catherine
