### ISSUE TITLE
Problem synchronization group/slice 

### ISSUE THREAD

**Issue by antool** [agroportal/agroportal_web_ui#124]
This curl command has no effect:
curl -X PATCH -H "Content-Type: application/json" -H "Authorization:apikey token=xxx" http://data.agroportal.lirmm.fr/slices/synchronize_groups

**Comment by vemonet** [comment]
Not patch, it is GET verb

curl -X GET -H "Content-Type: application/json" -H "Authorization:apikey token=XXXX" http://data.agroportal.lirmm.fr/slices/synchronize_groups

**Comment by antool** [comment]
Updated in the AgroPortal Admin Tool
