### ISSUE TITLE
Charger DURUM_WHEAT dans AgroPortal

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#16]
A voir avec Patrice et Stephane si c'est ok.
Je pense que Vincent a deja l'URL de pull.
Faudra compléter les autres metadonnées

**Comment by antool** [comment]
Tests en cours dans stagePortal : problème d'affichage des lettres accentuées et absence des métadonnées visant à décrire l'ontologie sur le portail. J'ai fait un mail à Stéphane pour régler ces points là.

**Comment by antool** [comment]
Ai contacté directement Patrice Buche. Problème des lettres accentuées réglé (mauvais encodage dans le fichier source de l'ontologie). Patrice a chargé DURUM_WHEAT dans AgroPortal en saisissant lui-même les métadonnées.
