### ISSUE TITLE
Charger toutes les ontologies (qui restent) de Cropontology.org (debuger, et maj la slice)

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#17]
L'objectif de ce tracker et d'assurer le suivi de l'upload de toutes les ontologies à partir de http://www.cropontology.org/

Pour le moment nous en avons 4. Nous avions prévu de mettre les autres quand la question de la pullLocation URL serait réglé.

Faudra saans doute débugegr au cas par cas, ainsi que compléter comme il faut les métadonnées.
Finalement mettre a jour la slice et le groupe CROP.

**Comment by jonquet** [comment]
Du nouveau la dessus ? C'est important pour le use case CO.

**Comment by antool** [comment]
Il y a huit ontologies pour l'instant.  J'ai créé le projet Crop Ontology en y associant les ontologies concernées. J'en ai profité pour mettre à jour la slice crop.

**Comment by antool** [comment]
Discussion en cours avec Marie pour charger d'autres ontologies "crop"

**Comment by jonquet** [comment]
J'ai mis a jour le GDoc de la liste des ontologies avec toutes les ontologies de cropontology.org.
Il faudrait compléter la liste des meta données et faire le point avec Marie/Elizabeth ontologie par ontologie.

**Comment by antool** [comment]
6 nouvelles ontologies ce jour

**Comment by antool** [comment]
La slice est mise à jour. On a un total de 14 ontologies crop à ce jour et au moins 7 à venir dans les prochaines semaines

**Comment by jonquet** [comment]
Peut tu compléter avec le delta ajouté aujourd'hui.
J'ai cru voir que la navigation de classes ne fonctionnait pas sur 2 ou 3 d'entre elles.
Qu'on fasse le suivi ici.

**Comment by antool** [comment]
Oui, j'ai vu. Je pense qu'il faut juste patienter, le temps que tout 
soit bien parsé dans le portail. La dernière fois, pour l'ontologie du 
riz, cela n'a été effectif que un à deux jours plus tard. Et là, j'ai 
balancé 6 nouvelles ontologies d'un coup, assez lourdes en plus.
Donc, ne touchez à rien et soyons patients ;-)
Ça devrait être "navigable" dans quelques heures. Pas la peine de faire 
un tracker pour l'instant, tout est noté dans le google drive.

Anne


Le 26/04/2016 15:29, Clement Jonquet a écrit :

**Comment by antool** [comment]
Il faut attendre quelques heures la fin du chargement sur le portail avant de pouvoir naviguer

**Comment by jonquet** [comment]
@antool et @marieALaporte  Est-ce que vous pouvez ecrire une mini synthese la:
- Combien d'ontologie de cropontology.org nosu avons? Sur combien total ?
- Les raisons principales pour ne pas avoir les autres encore?
- Le planing (dans les grandes lignes)

Et fermer le tracker ;)

**Comment by marieALaporte** [comment]
J’en saurais plus en Septembre. 
Je mettrais le tracker à jour à ce moment là.

**Comment by jonquet** [comment]
Visiblement le groupe crop ne contient pas les ontologies qu'il faut. A verifier la slice aussi pour les garder en sync. 
Voir Skype today.

**Comment by antool** [comment]
Il y a un problème avec deux ontologies CROP nouvellement chargées :
http://agroportal.lirmm.fr/ontologies/CO_334/
http://agroportal.lirmm.fr/ontologies/C0_340/
Pour l'instant, pas moyen de naviguer les classes ("Problem retrieving classes") alors que :
- si l'on regarde via l'api rest, tout semble ok ;
- il n'y a aucune erreur dans le fichier de log pour ces ontologies.
  Peut-être qu'il faut juste patienter encore.

**Comment by antool** [comment]
Problème réglé : il faut charger les ontologies au format OWL et patienter quelques minutes avant d'obtenir le bon affichage.

**Comment by antool** [comment]
Pour le suivi slice/group, voir agroportal/agroportal_web_ui#58
