### ISSUE TITLE
Change the hierarchy tree to display other relations for crop ontologies

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#21]
And display a hiearchy like the one on cropontology.org

**Comment by antool** [comment]
Nouvelle soumission de l'ontologie "riz" CO_320 à partir d'un fichier produit par Marie.
Pour l'instant, gros bug, impossible d'afficher les classes.

**Comment by jonquet** [comment]
Discuté avec Cyril Pommier en janvier 2016: si on renvoit un json au format Breeding API (aussi decrit ici: http://www.cropontology.org/TD_template_v5.xls 
Alors on pourrait graphiquement reutiliser un projet sur lequel il travaille: 
https://github.com/cpommier/trait-ontology-widget

**Comment by jonquet** [comment]
Il semblerait que la nouvelle version de CO_321 soit plutot bien présentée meme si pas exactement comme celle sur cropontology.org
Si cela est ok pour Marie et elizabeth, on restera la dessus.... en attendant d'avoir plus de reources pour AgroPortal et en attnedant d'avoir fait l'issue agroportal/agroportal_web_ui#24
