### ISSUE TITLE
Fix the URI used in the SPARQL endpoint

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#22]
We need to use our own URI for ontologies in the SPARQL endoint.
For instance:
   GRAPH http://data.bioontology.org/ontologies/PTO/submissions/1 
should be
   GRAPH http://data.agroportal.lirmm.fr/ontologies/PTO/submissions/1 

C'est pas grand chose, mais cela évitera la confusion avec le NCBO BioPortal.

**Comment by vemonet** [comment]
je suis d'accord
Mais tout le code est fait en sorte pour travailler sur la base d'URI "http://data.bioontology.org/" dans le SPARQL endpoint 
Ce qui se passe c'est que derrière on rajoute dans la config 

```
    config.rest_url_prefix    = "http://data.agroportal.lirmm.fr/"
    config.replace_url_prefix = true
```

Et à chaque fois qu'un projet récupère quelque chose dans le SPARQL endpoint il fait un replace sur l'URI pour remplacer par la notre
C'est pas très beau, mais c'est la façon de fonctionner du portail, ça pourrait être assez lourd à changer (et cela nécessiterait beaucoup de tests afin de s'assurer qu'aucune fonctionnalité n'est cassée)

**Comment by vemonet** [comment]
A noter que c'est quasiment impossible à faire car le NCBO a utilisé l'URI en dur un peu partout dans son code. Donc ça serait beaucoup de travail que de le changer (et il faudrait le faire sur une machine vierge) et de s'assurer qu'aucun projet connexe ne soit impacté.
Quelques exemples : 
- https://github.com/ncbo/owlapi_wrapper/blob/master/src/org/stanford/ncbo/oapiwrapper/OntologyParser.java#L322
- https://github.com/ncbo/ontologies_linked_data/blob/master/lib/ontologies_linked_data/mappings/mappings.rb#L6:L12

**Comment by jonquet** [comment]
@mdorf @alexskr 
I think this could be interesting for you to know when packaging the virtual appliance. 

The main idea is that the URI prefix:  http://data.bioontology.org/ is hardcoded in a bunch of places that prevent VA users to use their own previx in their own appliance.

**Comment by vemonet** [comment]
I dived a little bit in it, it should be possible to do it by changing "config.id_url_prefix" in config files

All the replace in the URI seems to be done here https://github.com/sifrproject/ontologies_linked_data/blob/master/lib/ontologies_linked_data/monkeypatches/object.rb#L153

We will need to make sure nothing has been forgotten (for example in owlapi_wrapper and else).

But we could try to implement it in the new docker installation

**Comment by jonquet** [comment]
Let's wait as this is not top priority. And maybe NCBO will have some feedback.

**Comment by jonquet** [comment]
Close for now. Will reopen per user request in the future.
