### ISSUE TITLE
Change PTO acronym by TO

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#23]
They really use "TO" as their acronym for IDs etc.
In AgroPortal we should alos use TO for http://agroportal.lirmm.fr/ontologies/PTO/

**Comment by vemonet** [comment]
Il faut supprimer l'ontologie et la recréer

**Comment by jonquet** [comment]
Je ferme cet issue. Cela a été fait. Merci Vincent.
