### ISSUE TITLE
Quand on crée un compte, faudrait qu'on soit ajouté à notre mailing liste

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#26]
Quand on crée un compte il y a une checkbox qui offre de s'inscrire a une mailing liste de BioPortal... ce qui ne se passe pas d'ailleurs.

Faudrait que chez nous cela implique une inscription a agroportal-users@lirmm.fr 
(que l'on peut faire a la main, si on a une notification qui dit que qq vient de creer un compte).
Je peux faire les inscritpions (j'ai les mains sur la mailing liste) maunellement;

**Comment by jonquet** [comment]
Vincent, as tu une notification quand qq crée un compte sur un de nos portail ?

**Comment by antool** [comment]
Non, on ne reçoit pas de notification (ni Vincent, ni moi).

**Comment by antool** [comment]
Vincent, pourrais-tu voir comment faire pour obtenir cette notification ?

**Comment by antool** [comment]
En cours.

**Comment by jonquet** [comment]
Suivi par email direct. On s'en occupe.

**Comment by jonquet** [comment]
Du nouveau la dessus ? 
On avait évoquer de faire un appel automatique a Sympa pour ajouter un membre sur la mainling list. 
Si c'est trop dur, on laisse tomber. Une fois de temps en temps je mettrai a jour la mailing list manuellement.

Dites moi.

**Comment by jonquet** [comment]
On gère cela à la main avec @antool. *
Liste mise a jour en avril 2017.
