### ISSUE TITLE
Chargement de nouvelles ontologies sur le portail

### ISSUE THREAD

**Issue by antool** [agroportal/agroportal_web_ui#28]
Discussion en cours avec 
- Claire Nédellec : ATOL (Animal Trait Ontology for Livestock)
- Sophie Aubin : ADO (Ontologie des maladies animales)
- Pierre Yves Le Bail et Sophie Aubin : EOL (Environment Ontology for Livestock)
Fichier mis à jour sur le google drive : IBC AgroPortal ontologies

**Comment by antool** [comment]
Cool ! Sophie s'occupe de déposer ATOL et EOL dès que leur problème de licence aura été réglé.
Pour ADO, c'est fait : reste à régler quelques problèmes d'affichage. Je m'en charge dès que j'aurai récupérer le fichier pour voir d'où viennent les problèmes.

**Comment by antool** [comment]
- Problème d'affichage dû au mélange de rdfs:label et skos:preflabel. Le portail récupère par défaut rdfs:label et ignore le skos:prefLabel. Du coup, si à un moment donné il n'y a pas de rdfs:label, aucun Label n'apparait. Sophie va modifier son fichier en conséquence
- problème du bilinguisme anglais/français

**Comment by jonquet** [comment]
Je vous propose de tester ces ontologies sur stageportal avant de les mettre sur AgroPortal. Il faut qu'on discute avec les gens (INRA, use cases) pour voir si oui ou non on inclus des ontogies liées aux animaux dans AgroPortal.

**Comment by jonquet** [comment]
En parallele, on travaille sur NALT, CABT et AGROVOC. Ces vocab sont importants.
Puis celle de cropontology.org

Bye the way, the new version of CO_321 est super classe !!

**Comment by jonquet** [comment]
Je ferme ce tracker (trop large) pour en ré-ouvrir un ontologie par ontologie.
