### ISSUE TITLE
Bug in the pull URL for ontologies coming from the NCBO BioPortal

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#29]
On a un cycle pour certiane ontologie: 
Notre  pull URL est notre service REST a nous:

E.g. NCBITAXON
La pull URL est
http://data.agroportal.lirmm.fr/ontologies/NCBITAXON/submissions/6/download?apikey=4a5011ea-75fa-4be6-8e89-f45c8c84844e

Il semblerait qu'il faille juste changer agroportal.lirmm.fr par bioontology.org et ca marche.

Idem pour 
GO, ENVO, CDAO, etc....

**Comment by vemonet** [comment]
Oui mais elles sont bien stockées dans 4store
C'est dû au fait que quand des données sont récupérées dans le triplestore, il y a un replace de http://data.bioontology.org/ par http://data.agroportal.lirmm.fr/ qui est fait pour toutes les données (vu que tout est enregistré avec l'URI http://data.bioontology.org/).

**Comment by jonquet** [comment]
Vincent:
Voila la ligne de code ou le changement est fait:
https://github.com/ncbo/ontologies_linked_data/blob/master/lib/ontologies_linked_data/monkeypatches/object.rb#L154

**Comment by jonquet** [comment]
Pour le moment le bug peut etre resolu en changeant les pullLocation avec qq chose avant l'URL e.g., 
http://nothing.bioontology.org/ontologies/NCBITAXON/submissions/6/download

Car tout ce qui est avant le nom de domaine est ramené au nom de domaine... 

Fait pour NCBITAXON, cela a l'air de marcher.
J'ai fais les autres ontologies de stageportal d'ailleurs

Quand on sera sur que c'est ok, a faire pour toutes les autres autres ontologies du NCBO BioPortal qu'on a dans AgroPortal et IFR BioPortal

**Comment by jonquet** [comment]
Je relance ce tracker pour qu'on fixe ca sur AgroPortal car sion les ontologies ne sont pas a jour.
Par exemple:
The AgroPortal entry for EFO http://agroportal.lirmm.fr/ontologies/EFO and (the original) BioPortal entry for EFO is http://bioportal.bioontology.org/ontologies/EFO You can see they are out of sync

Dans ce cas : 
http://data.agroportal.lirmm.fr/ontologies/EFO/latest_submission?display=all
On a un cycle sur la pullLocation (probleme discuté au dessus dans le tracker)

Alors qu’il nous faut la valeur qui est a : 
http://data.bioontology.org/ontologies/EFO/latest_submission?display=all

Anne, est-ce que tu pourrais parcourir les ontologies « qui sont aussi dans NCBO BioPortal » et renseigner proprement leur pullLocation :
-   Si il y en a une, la prendre
-   Si il y en a pas, mettre la combine avec le nothing

Cela permettra qu’on se branche soit a la source si il y en a une, soit au NCBO BioPortal, pour être à jour des que qq mets son ontologie sur le BioPortal

**Comment by jonquet** [comment]
Fait pour ENVO aujourd'hui a la main.

**Comment by jonquet** [comment]
Aucune des ontologies de stage n'ont changé pour pouvoir verifier le teste de "nothing.truc"
J'ai fait ce chght du coup: 
Pour GO j'ai mis la pullURL suivante: http://data.bioontology.org/ontologies/GO/download?apikey=4a5011ea-75fa-4be6-8e89-f45c8c84844e

On devrait savoir demain matin si cela marche.

**Comment by vemonet** [comment]
Si on met une URL en https ça résout le problème apparemment

Exemple :
https://data.bioontology.org/ontologies/EFO/download?apikey=4a5011ea-75fa-4be6-8e89-f45c8c84844e

**Comment by antool** [comment]
Modifications faites pour toutes les ontologies d'AgroPortal en provenance du NCBO BioPortal (y compris celle de OBO foundry). Google doc mis à jour

**Comment by jonquet** [comment]
Bon il semblerait qu'on ait toujours un petit decalage, ou que les choses ne soient pas prafaitement en sync. Par exemple: 
http://bioportal.bioontology.org/ontologies/EFO
http://agroportal.lirmm.fr/ontologies/EFO
Notre version 2.71 est du 30 mai. Leur version est du 18 avril, puis des erreurs apres cette date.

https://bioportal.bioontology.org/ontologies/GO
http://agroportal.lirmm.fr/ontologies/GO
Notre version est du 18 mai. Leur version est du 22 janvier.

http://bioportal.bioontology.org/ontologies/NCBITAXON
http://agroportal.lirmm.fr/ontologies/NCBITAXON
Mis a jour le 20 juillet par BioPortal. Mais pas mis a jour chez nous automatiquement.

A l'occasion faudrait qu'on clarifie un peu.

**Comment by vemonet** [comment]
Il y a pull seulement si la submission a été parsée : pour EFO et NCBITAXON on a bien les dernières submissions parsées.
Pour GO c'est bizarre, on semble avoir une version plus récente que le NCBO : "releases/2016-05-18" alors que leur dernière est la "releases/2016-01-22"

**Comment by vemonet** [comment]
Rappel: utiliser une adresse HTTPS résout le problème
`https://data.bioontology.org/ontologies/NCBITAXON/download`
