### ISSUE TITLE
Loading GACS / Agrisemantic ontologies: Agrovoc, NALt et CABt

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#35]
This tracker is to follow the inclusion of the 3 ontologies in AgroPortal.
Assigned to Anne to report last tentatives...; teh we will track here updates.

**Comment by jonquet** [comment]
Statut a l'heure actuelle: 

http://stageportal.lirmm.fr/ontologies/AGROVOCWB
Pas de classe navigable

http://stageportal.lirmm.fr/ontologies/CABTS
(il y a 14543 individuals skos et on peut pas les naviguer… j’avais peut être tout simplement pas mis le ‘top concept’ a tous dans ce fichier que j’avais fait)

 NALT
(a mettre sur Stage)
Fichier complet : https://www.sugarsync.com/pf/D7359850_05173488_496253
Sample moitié moins gros que j’avais préparé en mars : https://www.sugarsync.com/pf/D7359850_05173488_492756

**Comment by jonquet** [comment]
There is a browsable verison here:
http://browser.agrisemantics.org/gacs/en/?clang=lo

And a downloadable verion here: 
http://agrisemantics.org/gacs/

Can we test it on stage ?

**Comment by antool** [comment]
NALT est déjà sur Stage et pas navigable non plus : http://stageportal.lirmm.fr/ontologies/NALT
D'après les fichiers Log, qu'il s'agisse de Agrovoc, CABTS ou NALT, il y a un problème de label.

GACS : la version GACS Core Beta sur Stage fait apparaître une erreur au chargement : "(Uploaded, Error Rdf)"

Comme tous ces fichiers sont ultra gros, impossible de les ouvrir avec des outils traditionnels (sauf le sample Agrovoc de Armando). Il va falloir passer par les lignes de commande pour ouvrir ou extraire une partie de ces vocabulaires.

**Comment by antool** [comment]
Premier bilan après lecture des fichiers en ligne de commande : 
-  GACS ( 
  [gacs-core-beta-3.1.rdf.zip](https://github.com/agroportal/agroportal_web_ui/files/477027/gacs-core-beta-3.1.rdf.zip))

Premier problème : c'est du SKOS mais qui utilise aussi SKOS-XL (non pris en charge par AgroPortal)

Second problème : beaucoup de caractères spéciaux pour les labels en différentes langues (chinois, arabe, russe, etc)

Sinon, il y a bien des "hasTopConcept" donc pas de problème de ce côté-là.
- AGROVOC (
  [agrovoc_wb_20110223_v_1_3-smallcut_vocfixed.nt.zip](https://github.com/agroportal/agroportal_web_ui/files/477040/agrovoc_wb_20110223_v_1_3-smallcut_vocfixed.nt.zip))

problème identifié : il y a des "topConceptOf" mais pas de "hasTopConcept"
- NALT (
  [NAL_Thesaurus_2016_SKOS.rdf.zip](https://github.com/agroportal/agroportal_web_ui/files/477047/NAL_Thesaurus_2016_SKOS.rdf.zip))

Beaucoup de conceptScheme sont définis : j'en ai compté 17. Les propriétés "hasTopConcept" sont bien posées.

**Comment by antool** [comment]
- CAB Thesaurus (
  [cab-thesaurus-2016-sample-a-skos.rdf.zip](https://github.com/agroportal/agroportal_web_ui/files/477074/cab-thesaurus-2016-sample-a-skos.rdf.zip))

Pas de conceptScheme défini, et évidemment pas de "hasTopConcept"

**Comment by jonquet** [comment]
Quick update:
- AGROVOC: terms are indexed (ie. works in Annotator and Search)
  @antool Can you make a version with "hasTopConcept" and test again
- NALT: @antool can you write here the log issue. We need to understand.
    ADMIN StagePortal : "Error while running report on component sub.roots(): NoMethodError: undefined method `id' for nil:NilClass"
    Fichier log (pb récurrent) : No labels generated in page 11.
- CABT: the version seems to work. Except that the terms indexed are not the english ones e.g., acuarios instead of  aquaria. Could this come from the fact that the file use xml:lang="en-GB" instead of xml:lang="en"... certainement @antool Can you make a new version with ="en" and test again ?
- GACS: I have check the file.. this is not skos-xl in fact... there are 1 class that is using skos-xl. The content is not indexed by search and annotator. Why ? What are the issues identified for this vocab?
  @antool can you generate a version without the special characters if you think this is the issue...

FYI: the owl:Ontology object is line 3282355... weird... the main metadata are on the skos:ConceptScheme object at the beginning of the file

By the way, all files open with Notepad++

**Comment by antool** [comment]
NALT : tests 22 octobre 2016
1) Un extrait du fichier sur StagePortal : http://stageportal.lirmm.fr/ontologies/NALT-TEST
-> Ça marche, modulo un petit problème d'encodage (lettres accentuées espagnoles)
2) Le fichier complet sur StagePortal : http://stageportal.lirmm.fr/ontologies/NALT-2016
-> Ça marche difficilement mais c'est un problème de gestion par le portail : ça rame un maximum, on n'arrive pas à afficher tous les termes ni à naviguer. Probablement un problème d'échelle : pour l'instant, StagePortal n'arrive pas à gérer une si grosse terminologie (63096 termes).
3) Test en cours sur AgroPortal (mode privé) : http://agroportal.lirmm.fr/ontologies/NALT-2016

**Comment by antool** [comment]
NALT : problème d'encodage résolu ici : 
http://stageportal.lirmm.fr/ontologies/NALT-TEST-UTF8
Le fichier d'origine est encodé en Western (ISO LATIN 1) mal pris en charge dans le cas des lettres accentuées espagnoles. Ré-encoder en UTF8 résout le problème d'affichage

**Comment by antool** [comment]
NALT sur AgroPortal : même problème que sur stage. L'ontologie est parsée, indexée, etc ; il n'y a pas d'erreur répertoriée pour cette ontologie. Mais impossible d'afficher les classes et de les naviguer. Cela vient-il du fait que portail n'est pas conçu pour gérer des terminologies aussi grosses ?

**Comment by antool** [comment]
Pour l'affichage et la navigation des classes, il s'agit probablement d'un problème dans l'UI. Quand on passe par l'API REST, on obtient toutes les classes : 
http://data.stageportal.lirmm.fr/ontologies/NALT-2016/classes
http://data.agroportal.lirmm.fr/ontologies/NALT-2016/classes

**Comment by jonquet** [comment]
Voir email specifique NALT de Clement a Anne du 24/10

**Comment by jonquet** [comment]
Je reprends ici. 
Je crée NALT dans AgroPortal et tente la version 2015 (comme ca si ca marche on aura les 2). 
Je crée un tracker spécifique pour chacun: 

- NALT: agroportal/agroportal_web_ui#99
- CABT: agroportal/agroportal_web_ui#100 
- GACS: agroportal/agroportal_web_ui#101
