### ISSUE TITLE
Mettre à jour la slice exclu

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#36]
Apres les ajouts recents et a chque ajout suivant il faut penser a mettre a jours les slices.
Celle la est important car elle donne le nombre d'ontologie chez nous et pas chez BioPortal.

**Comment by antool** [comment]
Slice mise à jour le 31 mai : 21 ontologies

**Comment by antool** [comment]
Slice mise à jour le 27 juin 2016 : ajout des ontologies LEXEAU et PO2
23 ontologies
Le document "AgroPortal ontologies" a été mis à jour également.

**Comment by antool** [comment]
28 juin 2016 : ajout de l'ontologie CROPUSAGE
24 ontologies dans la slice, document "AgroPortal ontologies" mis à jour.

**Comment by jonquet** [comment]
@antool Je ferme ce tracker, bien que ce soit une tache a refaire régulièrement (quand on recoit une notification d'une nouvelle ontologie)
