### ISSUE TITLE
Adding metadata fields in the submission form for an ontology

### ISSUE THREAD

**Issue by antool** [agroportal/agroportal_web_ui#38]
In the perspective of the coordination between VEST and AgroPortal, we need to add some metadata fields.
Valeria. "Allowing the registration of vocabularies with only metadata in the AgroPortal (adding a few metadata to the basic initial registration: description, owner/publisher, vocabulary type, domain, format, license)"
Clément. "For metadata form : Name (you have it already), Description, Owner/publisher, Vocabulary type, Domain(s) (I think you already have the categories?), Format
We need to :
- add publisher (with open values) 
- add type (with restricted values)
- add the categories as discussed in previous response."

**Comment by saubin78** [comment]
For types, we can consider the list for VEST that was discussed some time ago with Imma [https://docs.google.com/spreadsheets/d/1mwgnE7nKyZX4AbMuktLW2sxoSpBvm7zo7YhGoVO26JM/edit#gid=4]. Types are described

**Comment by jonquet** [comment]
- For the domain/categories, this is the only list that is materialized within the portal. I am ok with the one in the file. 
- For license and types these fields are not restricted. They are property values. What we can do eventually is to offer a pop up with those values when someone upload a "metadata only ontology". 
- For format, this property is selected only for ontologies with real content. So we can offer here also a pop up for someone to select  another format when registring a metadata only ontology. 

In both cases our philosophy is to encourage the use of URI for thoses values, so I would prefer to see values that are URIs. 
@saubin78 do you have a reference for Dublin Core type ?

**Comment by saubin78** [comment]
Look here
http://nkos.slis.kent.edu/nkostype/nkostype.rdf

**Comment by valeriapesce** [comment]
For the list of "vocabulary types", in the Google spreadsheet that  Sophie shared there is a list coming from Dublin Core: http://wiki.dublincore.org/index.php/NKOS_Vocabularies#KOS_Types_Vocabulary (they have definitions and URIs).
Since that DC list is only for KOS types, but we also have metadata schemas, we added three types to that list in the VEST (the last three in this list):

Name authority list
Classification scheme
Dictionary
Encyclopedia
Glossary
Lexical Database
Ontology
-Domain ontology
-Ontology type2 (here we were thinking of including all the ontology types you have in AgroPortal)
Subject heading scheme
Taxonomy
Terminology
Thesaurus
Topic Tree
Gazetteer
RDFS description vocabulary
Metadata schema
Application profile

**Comment by valeriapesce** [comment]
For formats, we proposed the list below (also in Sophie's spreadsheet at https://docs.google.com/spreadsheets/d/1mwgnE7nKyZX4AbMuktLW2sxoSpBvm7zo7YhGoVO26JM/edit#gid=5): the URIs can be taken partly from W3C (https://www.w3.org/ns/formats/) and partly from IANA (http://www.iana.org/assignments/media-types/media-types.xhtml).

Do you want me to compile a table with definitions and URIs?

I can add them to Sophie's spreadsheet.

Plain text
CSV
TSV
Spreadsheet (xls/xslx)
Turtle
Notation3
N-Quads
N-Triples
JSON-LD
RDF/JSON
RDF/XML
RDF/TriG
OWL/XML
OBO Flat File
OBO/XML
TBX/XML
HTML
RDFa
PDF
MDB

**Comment by jonquet** [comment]
Sounds good to me to use NKOS for types and W3C formats. Thanks for the reference to NKOS Sophie. We didn't knew this.
For the format, I recall that the property that will have those values willa ctually be called omv:hasOntologySyntax in AgroPortal. The property hasOntologyLanguage (Format) is actually used by AgroPortal to know which parser to use, thus we will not use this for the moment.

Can someone please complete the URI columns in Sophie GDoc for tab "KOS types" and "mediaType".

Then we can assign to Vincent for him to have a look at it.

**Comment by jonquet** [comment]
Version on stage seems to work properly.
Il y a quand même un probleme avec la propriété affectée. E.g. :
http://data.stageportal.lirmm.fr/ontologies/MSHFRE/latest_submission?display=all
Dans le cas de hasOntologySyntax c'est bien une URI, mais pas dans le cas de hasFormalityLevel ou c'est une chaine de caractere au lieu d'etre l'URI dnas DCMI KOS.

In the U I would rename: "has ontology syntax" by just "Syntax" and "has formality level" by 'Formality Level".
- A droite de Formality level, ajouter la phrase: "Properties taken from DCMI KOS type vocabularies" avec un lien vers l'URL mentionné ci dessus.
- A droite de Syntax, ajouter la phrase: "Properties taken from W3C URIs for file format. avec un lien aussi
- A droite de License, ajouter la phrase: "Open property, use URI if possible"

**Comment by vemonet** [comment]
URI for hasFormalityLevel has been pushed to stage
Wouldn't it be better to keep "hasOntologySyntax" to avoid misleading labels?

**Comment by jonquet** [comment]
OK vu pour formality level et pour les commentaires.
POur Syntax, tu as cas mettre "File Syntax" ou "Ontology Syntax"
Apres ca, on pousse en prod et on ferme le tracker.

**Comment by vemonet** [comment]
Pushed on Agroportal
