### ISSUE TITLE
Submit projects in AgroPortal UI for AgroPortal primary users

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#4]
Project to submit includes: 
Crop Ontology
LovInra
RDA Wheat
AgroLD
Planteome
Others...

This can be done through the UI (by Anne) then projects need to be reassigned to their actual users in AgroPortal... it needs to be done by a REST POST call
I am assigning to Vincent to copy/paste the CURL call.

**Comment by vemonet** [comment]
curl -X POST -H "Content-Type: application/json" -H "Authorization: apikey token=YOUR API KEY!" -d '
{
  "creator" : ["http://data.agroportal.lirmm.fr/users/USERNAME"],
  "acronym" : "ACRO",
  "name": "Nom du projet",
  "homePage" : "http://www.lirmm.fr/",
  "description" : "Description du projet",
  "contacts" : "Nom du Contact",
  "institution" : "LIRMM Université de Montpellier & CNRS",
  "ontologyUsed" : ["STY", "CIF"]
}' http://data.agroportal.lirmm.fr/projects

**Comment by jonquet** [comment]
Anne, il faut que tu les saisisse toi et que tu les « affecte » ensuite via l’admin aux utilisateurs « logiques » dans AgroPortal. Ensuite, il faut faire un email pour dire : « on a mis ce projet dans le portail, est-ce que cela vous va ? »

**Comment by jonquet** [comment]
Du nouveau ?

**Comment by antool** [comment]
Projet Crop créé (vu avec Elizabeth et Marie), chargement des ontologies mis à jour (8 ontologies du groupe crop) ainsi que la slice.

**Comment by antool** [comment]
Autres projets créés :
- Planteome (3 ontologies associées : EO, PO, TO)
- LOVinra  (3 ontologies associées : ONTOBIOTOPE, TRANSMAT, WHEATPHENOTYPE)
- RDA Wheat (pas d'ontologies pour l'instant, à voir ce que l'on pourrait y accrocher)

**Comment by antool** [comment]
Suite à des échanges avec Claire Nédellec, création de deux projets : OntoBiotope et Sélection du blé tendre assisté par marqueur (FSOV SAM blé).
Je clos cette discussion même si la création de projets reste d'actualité !
