### ISSUE TITLE
Modification of AgroPortal's categories

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#40]
We open this to track the process of changing the AgroPortal's categories:
http://data.agroportal.lirmm.fr/categories

This tracker should be closed when new categories will be in AgroPortal AND when existing ontologies will be assigned to new categories.

**Comment by jonquet** [comment]
ANNE (20/07):
I made a new document to work easily with the categories :
https://docs.google.com/spreadsheets/d/1Jx8lHfYXHA8elIlkmZ1AsPyRBUxYC-dQsSdcSqvRelc/edit#gid=980042183

Valeria, you can write here the descriptions for each category and give them an acronym too.
Sophie, as you can see, we have few sheets in this document and especially all the ontologies in AgroPortal with their category and group.
When I'll have all the details, I'll create the new categories, and after that, it will be fine to talk with you about "which category for which ontology".

**Comment by jonquet** [comment]
ANNE (20/07): I created the new categories in AgroPortal (maybe you won't be able to see them just now, platform needs a moment to process), except for "Taxonomic Classifications of Organisms", because of the discussion on the name and description (see google doc).

What I have to do now :
1) Modify the relations between ontologies in AgroPortal and their categories ;
2) remove the old categories
This will be done before the weekend.

**Comment by jonquet** [comment]
Dont forget to rename the previous categories by removing the code from the name.

**Comment by jonquet** [comment]
ANNE (21/07) : 
Pour info : lorsqu'on supprime une catégorie, on ne peut plus naviguer les ontologies qui y étaient associées. Mais du coup, il y a quand même quelques bugs sur certaines (en particulier celles qui étaient accrochées à "700-799 Location and Environmental" (catégorie supprimée).
J'espère avoir réglé cela avant le we.

**Comment by jonquet** [comment]
Je propose de finir cette tache avant les vacances et fermer le tracker.

**Comment by saubin78** [comment]
est-ce que je peux être utile ?

**Comment by jonquet** [comment]
Vous pouvez virer la catégorie "    Reference ontologies for plant"

**Comment by jonquet** [comment]
Est-ce qu'on peut fermer ce tracker ?

**Comment by antool** [comment]
L'ontologie "CROPUSAGE" est associée à la catégorie " Reference ontologies for plant", mais on peut changer.
Question restée en suspens : faut-il supprimer cette catégorie ?

**Comment by jonquet** [comment]
Oui il faut associer CROPUSAGE a une autre chose et supprimer cette catégorie.

**Comment by antool** [comment]
14/9/2016 : les catégories sont à jour, issue terminée
