### ISSUE TITLE
Exporting AgroPortal content to VEST Registry

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#41]
This issue concerns the development of an extractor to export the content of AgroPortal to the VEST Registry.
This track was started during the 1st AgroHackathon.

**Comment by jonquet** [comment]
CLEMENT: 
We will push into production (on agroportal.lirmm.fr) the listing currently on our staging server by next Wednesday. Hopefully this change will not break anything in AgroPortal (because a little more testing will be necessary). Should be ok. In a first time there will be only the new model (i.e., properties will be there to be returned/written via the API) but they will be no UI to actually fill them up 

VALERIA: However, our test was indeed with “the listing currently on our staging server” and the /submissions API call on the staging server didn’t include many of the new or even old properties (category, owner / publisher…).

CLEMENT: 
Yes. This is because we changed the model (the storage of the metadata) but we don't have any additional metadata populated in the staging server. One in production we will start interacting with agroportal's users to actually populate the values. 

VALERIA:
Do you mean that when the properties are empty they don't appear at all in the API response, not even as empty? We couldn’t find the Json labels for them, so we could not set up the importer properly.
If you think that it’s only an issue of values that are not there and the Json properties will appear in the response once the values are there, that’s fine!

Actually, for filling those properties, our survey could be the perfect opportunity: if as you say people can login and request authority to modify a record we can send all the recipients of our first email (the vocabulary owners) the link to the AgroPortal to edit their vocabulary and add this missing information.
Would that work?

**Comment by jonquet** [comment]
@valeriapesce Normally the fields should appear if you use the &display=all option in the REST call
E.G., 
http://data.agroportal.lirmm.fr/ontologies/CO_321/latest_submission?display=all

Indeed, we gonna need to pass over our resources (now that the new metadata model is in production AgroPortal) and either us or other fill the properties. Otherwise, VEST will grab a bunch of not fully described ontologies.

**Comment by valeriapesce** [comment]
@jonquet The problem is that the API call you give above as an example is the call to the individual ontology submisison, while we call the general /submissions API call to get all the submissions at once, and that API response doesn't seem to include all these properties even if you add display=all.

**Comment by jonquet** [comment]
Humm... are you sure ? It seems that it does: 
http://data.agroportal.lirmm.fr/submissions?display=all&display_context=false&display_links=false

**Comment by jonquet** [comment]
@valeriapesce Is this ok now ?

**Comment by jonquet** [comment]
I close this issue as it is taken care now by @valeriapesce
