### ISSUE TITLE
Bug sur l'affichage des URIs au lieu des nom pour "has formality level" et "has format"

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#48]
Sur AgroPortal. Loggé admin.
Je viens de changer a la main ces propriététés pour Biorefinary et c'est les URI qui s'affichent desormais dans l'UI.
http://agroportal.lirmm.fr/ontologies/BIOREFINERY

Pour info: idem pour la propriété natural language. C'est l'URI qui s'affiche. Faudrait que ce soit le nom de la langue en anglais.

**Comment by vemonet** [comment]
C'est normal. On ne stocke que l'URI, pas le label qui est juste indicatif et totalement arbitraire. Donc on affiche l'URI quand on récupère les données. On peut faire du had'hoc en résolvant certains champs cela dit

Pour les languages je résouds seulement quand il y a l'URI lexvo, ou aussi quand on a les abréviations "fr", "fra" ?
Si on ne résouds pas les URIs en récupérant leurs valeurs via linked data, ça devient tout de suite super lourd en obligeant à créer des objets contenant les mappings URI > valueur

**Comment by vemonet** [comment]
Ca apporte quoi de résoudre les URIs au niveau de l'UI ? Les services comme VEST resgistry vont s'approvisionner au niveau de l'API REST de toute façon donc ils récupéreront l'URI (et tant mieux, un label ça ne vaut pas grand chose)

**Comment by jonquet** [comment]
Pour l'UI c'est une question d'interface utilisateur. L'UI est faite pour les humains qui préfèrent les chaines de caractères aux URIs.
Donc ca implique d'avoir qq part (coté UI ou coté modèle) une hashmap qui contient la conversion URI/label. Soit coté UI. Soit tu stocke dans le modele un objet complexe {label, URI}.
=> Ce que je suggère c'est que dans l'UI, ce soit le label qui s'affiche et qu'il soit clickable vers l'URI (qui on l’espère dereferencera vers la bonne URL).

Donc pour les propriétés fermées (comme formality level et syntax) pas de problème. Puisque c'est fermée.
Pour natural langage qui est ouverte, oui je suggère qu'on affiche dans l'UI le label de la langue que quand c'est l'URI Lexvo (ou le code ISO) qui est donné. (d'ailleurs ajoute ca a droite du champ: "We recommend the use of Lexvo URI with ISO639-3 codes" et pour Lexvo URI tu fais le lien a http://www.lexvo.org/)

**Comment by vemonet** [comment]
Il me semble que c'est résolu (sur Agro et BioPortal). Des suggestions ?

**Comment by jonquet** [comment]
Je ferme ca apres la release du 15/02 en prod
