### ISSUE TITLE
Petite amelioration de base de la page "Add submission metadata"

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#49]
- Virer les champs qui sont deja dans les autres pages (e.g., homepage, publication, status, etc.)
- Utiliser le nom des propriétés colonne B de notre GDoc plutot que le nom RDF de la propriété 
- Aligner tous les champs a remplir a l'aide d'une tabulation
- Faire des champs plus gros que d'autres e.g., notes, keywords
- Indiquer a droite du champ (aligné a droite comme fait dans la page edit submission) le type de propriété atetndu (String , URI etc.)
- Pour natural language, faire comme pours has formality level et has syntax... donné le lien vers le site qui donne des URI (voir GDoc)
- Virer les metadonnées qui peuvent être remplies automatiquement e.g. openSearchDescription, uriRegexPattern, exampleIdentifier

Aussi, quand on a deja rempli un champ, et qu'on revient sur la page Add metadata, faut qu'on le voit !
Sinon on ne peut plus modifier qq chose de déjà saisi.

@vemonet @antool Une partie de moi se demande si on ne devrait pas tout mettre sur la page "edit submission", en suivant le même patern et en cachant les métadonnées additionnelles sous un "Click here to add additionnal metadata to your submission"

**Comment by jonquet** [comment]
Pour info: funded by demande une URL, pour quoi ? Ca fait bizarre que lui le demande tandis que les autres (endorsed by, publisher, etc)

**Comment by jonquet** [comment]
Petits bugs:
- devant endorsedBY il y a une virgule
  http://agroportal.lirmm.fr/ontologies/BIOREFINERY
- virer les "has" de avnt contributor et creator et mettre un s a la fin

**Comment by vemonet** [comment]
- Virer les champs qui sont deja dans les autres pages (e.g., homepage, publication, status, etc.)
  Fait
- Aligner tous les champs a remplir a l'aide d'une tabulation
  Fait, sur stage
- Faire des champs plus gros que d'autres e.g., notes, keywords
  Fait sur Stage
- Indiquer a droite du champ (aligné a droite comme fait dans la page edit submission) le type de propriété atetndu (String , URI etc.)
  Fait, sur stage
- Pour natural language, faire comme pours has formality level et has syntax... donné le lien vers le site qui donne des URI (voir GDoc)
  Fait, sur stage
- Virer les metadonnées qui peuvent être remplies automatiquement e.g. openSearchDescription, uriRegexPattern, exampleIdentifier
- Aussi, quand on a deja rempli un champ, et qu'on revient sur la page Add metadata, faut qu'on le voit !
  Je n'affiche plus les metadata déjà remplies (il s'agit d'ajouter des metadata, pas de les editer)

Pour le moment il y a coupure de courant au LIRMM, donc je met à jour stage dès que c'est revenu

**Comment by jonquet** [comment]
Pour "License".

A coté du champ de saisie, indiquer l'aide suivante: 
"Consider using a URI to describe your License: http://rdflicense.appspot.com"
Et en dessous: 
"Don't know which License to use, consider using: http://licentia.inria.fr/"

**Comment by jonquet** [comment]
De facon similaire, pour Language:
"Consider using a URI (with ISO639-3 code) to describe your languages e.g., http://lexvo.org/id/iso639-3/eng (check out: http://lexvo.org)"

Mais l'idéal serait même d'avoir un pop-up dans lequel sélectionner.

**Comment by jonquet** [comment]
Pour le champ "has formality level":
POur le moment l'UI indique:
![image](https://cloud.githubusercontent.com/assets/7379183/22447062/07bc9b58-e705-11e6-9e25-107ee40b68ce.png)

Qui est censé être en sync avec:
http://wiki.dublincore.org/index.php/NKOS_Vocabularies#KOS_Types_Vocabulary

Ok pour enlever: categorization scheme et semantic network et synonym ring qui ne servirosn pas sur le portail...
Par contre, je garderai "list".
En outre, d'ou sort "Topic tree" ? SAns doute a enlever.

**Comment by jonquet** [comment]
Pour le champ "general type" (dc:type), je proposerai (pour éviter le conflit avec "has formality level" : 

- Application Ontology
- Domain Ontology
- Task Ontology
- Upper Level Ontology
- Vocabulary

**Comment by jonquet** [comment]
Pour info, quand on a saisi une métadonnée dans "Edit ontology submission" et qu'on revient plus tard a nouveau dans "Edit ontology submission", les metadonnées préalablement saisie n'apparaissent pas dans les champs proposés... qui sont des pop menus. Les pop-up affichent "none"...  (cependant les metadonnées ne sont pas réinitialisées si on ne rempli pas a chaque fois tous les champs).

Est-ce qu'on pourrait dans l'UI d’édition "affecter" les champs qui sont déjà remplis ?

**Comment by saubin78** [comment]
dc:type est généralement utilisé pour typer les ressources à un niveau "supérieur ": image, dataset... 
Cf http://dublincore.org/documents/dcmi-type-vocabulary
Ce ne sont que des recommandations mais c'est aussi ce qui est utilisé par Datacite pour attribuer les DOIs. Ce n'est peut-être pas judicieux de proposer cette liste spécifique aux ontologies pour la propriété dc:type.
Pour info, les valeurs généralement utilisées sont:
Audiovisual 
Collection 
Dataset 
Event 
Image 
InteractiveResource 
Model 
PhysicalObject 
Service 
Software 
Sound 
Text 
Workflow 
Other   
Je serais plutôt partisane de proposer une valeur par défaut pour toutes, à savoir "Model". A discuter ?

**Comment by jonquet** [comment]
Hum. Oui en fait j'ai vérifié.. je me suis trompé hier. Nous n'avions pas pris la propriété dc:type de Dublin Core dans le modèle implémenté en juillet dernier. Je n'aimais pas en effet cette généralité. Une métadonnée n'est pas réellement utile dans le portail si toutes les entrées ont la même valeur. Dans un dataset qui mélangerai différents types de données, ce serait pertinent et oui il faudrait alors dc:type:Model ou creer/accepter dc:type:Ontology.
Nous avons pris omv:isOfType qui est spécifique aux ontologies.

Donc dans l'interface @vemonet  je propose de restreindre les valeur de omv:isOfType aux 5 valeurs précédentes.

**Comment by vemonet** [comment]
J'ai modifié les valeurs par défaut pour correspondre à ce qui a été donné ici (sur stageportal pour l'instant)

**Comment by jonquet** [comment]
Pour le champ "metadataVoc", je proposerai d'utiliser la liste dans le GSheet:

rdfs	http://www.w3.org/2000/01/rdf-schema#
owl	http://www.w3.org/2002/07/owl#
skos	http://www.w3.org/2004/02/skos/core#
dc	http://purl.org/dc/elements/1.1/
dct	http://purl.org/dc/terms/
omv	http://omv.ontoware.org/2005/05/ontology#
mod	http://www.isibang.ac.in/ns/mod#
door	http://kannel.open.ac.uk/ontology#
voaf	http://purl.org/vocommons/voaf#
void	"http://rdfs.org/ns/void#
idot	http://biomodels.net/vocab/idot.rdf#
vann	http://purl.org/vocab/vann/
dcat	http://www.w3.org/ns/dcat#
adms	http://www.w3.org/ns/adms#
schema	http://schema.org/
foaf	http://xmlns.com/foaf/0.1/
doap	http://usefulinc.com/ns/doap#
cc	http://creativecommons.org/ns#
prov	http://www.w3.org/ns/prov#
pav	http://purl.org/pav/
oboInOwl	http://www.geneontology.org/formats/oboInOwl#

**Comment by jonquet** [comment]
Petit ajout supplémentaire: 
Autour des champs de propriété faire un petit bouton "suggested properties" qui fera apparaître des propositions a copier coller pour aller plus vite incluant (les URI complète):
rdfs:label
rdfs:comment
rdfs:isDefinedBy
rdfs:seeAlso
skos:notation
rdf:value
skos:note
skos:notation
owl:deprecated

**Comment by jonquet** [comment]
Homepage est la 2 fois.
Je suis pas arrivé a éditer hompage et isOfType pour MSHFRE.  A voir. 

Edit Vincent: Homepage fixed, isOfType semble modifié http://bioportal.lirmm.fr/ontologies/MSHFRE

**Comment by jonquet** [comment]
@vemonet Ca avance comment les regroupements ?

**Comment by jonquet** [comment]
Je ferme ce trackker suite au passage en prodcution de la nouvelle interface il y a qq jours.
