### ISSUE TITLE
Deploy slices for each group of ontologies

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#5]
We have fixed now the slice feature. For instance: http://wheat.agroportal.lirmm.fr
We now need to deploy all the slices defined in the GDoc 
https://docs.google.com/spreadsheets/d/1Jx8lHfYXHA8elIlkmZ1AsPyRBUxYC-dQsSdcSqvRelc/edit#gid=800725135

**Comment by vemonet** [comment]
Fait pour : 
http://crop.agroportal.lirmm.fr
http://wheat.agroportal.lirmm.fr
http://lovinra.agroportal.lirmm.fr

Manque que exclu (voir avec Anne quelles sont les ontologies à mettre dedans)

**Comment by jonquet** [comment]
Fait aussi pour http://agrold.agroportal.lirmm.fr/
J'ai mis a jour le GDoc aussi pour qu'on reste en sync.

Pour exclu... faut juste y mettre dedans toutes les ontologies qu'on est les seuls a avoir (= qui ne sont pas dans le NCBO BioPortal)... d'ailleurs, cela m'arrangerai de l'avoir pour samedi.

**Comment by vemonet** [comment]
http://agrold.agroportal.lirmm.fr
http://exclu.agroportal.lirmm.fr
