### ISSUE TITLE
Quelques ajouts groupe/slice

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#51]
Ajouter GENO a la slice "wheat"
Elle manque a la slice. Je l'ai ajouté au groupe, mais pas a la slice.
Ajouter GENO a la slice "wheat".

A y être faudrait peut etre ajouter DURUM_WHEAT aussi, quitte a demander a Esther avant car c'etait pas dans leur recensement (slice et groupe).

**Comment by jonquet** [comment]
A y être faudrait peut etre ajouter DURUM_WHEAT aussi, quitte a demander a Esther avant car c'etait pas dans leur recensement (slice et groupe).

**Comment by jonquet** [comment]
A y etre on va mettre aussi a jour la slice "lovinra".
Faut y mettre: TRANSMAT, WHEATPHENOTYPE, ADO, ONTOBIOTOPE, et la future MS2O.

**Comment by jonquet** [comment]
@saubin78 Est-ce que tu peux charger MS2O dans AgroPOrtal ? Et sans doute aussi mettre DURUM_WHEAT dans votre Lovinra. Comme ca on reste en sync.

@saubin78 Faudrait peut etre harmoniser les noms des ontologies dans les 2 plateformes pour que ce soit plus clair. 

Si tu as besoin des droits d'admin sur toutes les ontologies du groupes lovinra (en gros celles uploadées par l'INRA) @antool peut te les donner. Comme ca tu gardes la main dessus. Et comme on va bientot solliciter les gens pour l'ajout de métadonnées (maintenant que le nouveau modele est en prod... Vincent travaille sur l'UI) ben tu pourras sans doute le faire pour les onto de l'INRA. J'ai deja fait un peu de BioRefinery.

**Comment by saubin78** [comment]
ok pour MS2O et DURUM_WHEAT
Pour les noms, j'utilise le développé comme non préférentiel et l'acronyme comme alternatif. Reste la question de la langue. j'avais tendance à préférer la version française sur Lovinra mais je peux changer, ça n'a pas vraiment d'importance
Merci @antool de m'accorder les droits sur les ontologies INRA. Ce sera plus commode.
A+

**Comment by jonquet** [comment]
@saubin78 Il y a aussi PO2 déposé par Stepahen et TRIPHASE déposée par Claire, et PLATHO déposé par Cyril. Je te laisse voir si tu les inclus dans le groupe INRA... dit le nous qu'on change (slice, projet, etc.)

**Comment by jonquet** [comment]
@antool EDAM a ajouter dans la slice WHEAT et le groupe et le projet.

**Comment by saubin78** [comment]
Il semble y avoir un problème avec MS2O, comme si elle n'avait pas de "submission". J'ai le fichier, je peux le charger. Est-ce qu'il y a eu un problème ?

**Comment by saubin78** [comment]
J'ai contacté Cyril et Pierre pour PLATHO. En attente.
J'ai ajouté PO2 au groupe LOVINRA, je ne sais pas comment l'ajouter à la slice mais il faudrait le faire.
TRIPHASE n'est pas (encore) un Linked Open Vocabulary. On doit travailler avec eux là-dessus donc en attente
Notre problème c'est que les chercheurs INRA aiment trop AgroPortal et qu'ils ne passent pas par notre service pour publier ;-)

**Comment by saubin78** [comment]
Impossible de charger le fichier MS2O : something went wrong... mais je ne sais pas quoi.
[ms2o_core.zip](https://github.com/agroportal/agroportal_web_ui/files/399006/ms2o_core.zip)

**Comment by jonquet** [comment]
Pour MS2O, oui j'ai le meme probleme. On regardera avec @antool a la rentrée. 
Faudra leur dire de mettre des labels quand meme dans l'ontologie. Sinon ca rendra pas grand chose ;)

Pour modifier la slice INRA, @antool peut t'indiquer comment faire, pour que tu puisses le faire a chaque fois (desolé c'est pas automatique)

**Comment by saubin78** [comment]
ok. Question : s'il n'y a pas de labels, est-ce que c'est la dernière partie de l'URI qui s'affiche (ex: Operand1 pour http://opendata.inra.fr/ms2o/Operand1) ?

**Comment by saubin78** [comment]
J'ai mis MS2O en privé avec accès à Anne, Vincent et Clément en attendant la résolution.

**Comment by jonquet** [comment]
Pour MS2O suite dans agroportal/agroportal_web_ui#52

**Comment by antool** [comment]
Voir la suite de la discussion slice par slice agroportal/agroportal_web_ui#56 et agroportal/agroportal_web_ui#57
