### ISSUE TITLE
Chargement de MS2O

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#52]
Ce tracker prend la suite de #51 sur le chargement de MS2O seulement.

J'ai réessayé ce matin et cela marche sans problème. 
Comme il n'y a pas de label dans l'ontologie c'est la fin de l'URI qui est prise par défaut.

**Comment by jonquet** [comment]
@saubin78 tu regardes ?

**Comment by saubin78** [comment]
C'est parfait ! merci

**Comment by jonquet** [comment]
Je ferme le tracker, a ré-ouvrir si problème sur cette ontologie.
