### ISSUE TITLE
Chargement de OAE

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#54]
Essai fait par Anne Tireau la première fois. 
Le fichier est la:
[oae-3.0.owl.zip](https://github.com/agroportal/agroportal_web_ui/files/445442/oae-3.0.owl.zip)

@saubin78 prend le relai.

**Comment by saubin78** [comment]
Je ne suis pas très familière avec la représentation qu'ils ont utilisé (qui correspond pourtant aux recommandations W3C pour OWL 2)
Est-ce que le parser AP sait reconnaître les Declaration, AnnotationAssertion, SubObjectPropertyOf etc. ?

**Comment by saubin78** [comment]
Ce qui me semble particulier également c'est l'utilisation des "IRI" pour faire référence aux entités:    <IRI>#AgriActivity</IRI> 
Dans Lov'Inra, nous proscrivons leur usage ainsi que celui les # comme séparateur de fin dans les noms de domaine car les 2 nous posent des problèmes pour le déréférencement avec Pubby.

**Comment by antool** [comment]
Ontologie chargée sur AgroPortal le 8/9/2016 sans problème

**Comment by jonquet** [comment]
C'est a dire ? tu as refait un essai de chargement et c'est passé ? ou est-ce que tu as identifié et reglé un problème ?
(faut qu'on sache pour la prochaine fois... même si on a rien fait entre deux... c'est deja arrivé avec AFEO).

**Comment by antool** [comment]
J'ai comparé le fichier avec OFPE qui utilise le même formalisme. Comme tout avait l'air raccord, j'ai soumis sans modification et s'est passé comme une lettre à la poste

**Comment by jonquet** [comment]
Tant mieux. Mais c'est quand même bizarre ! Faut qu'on y pense.

**Comment by saubin78** [comment]
Il faudra que je refasse des tests. J'ai pas les bons tuyaux ou quoi ?
