### ISSUE TITLE
Slice/Group Lovinra

### ISSUE THREAD

**Issue by antool** [agroportal/agroportal_web_ui#56]
@saubin78 : les ontologies suivantes sont-elles toutes à étiqueter "LovInra" :

WHEATPHENOTYPE
ONTOBIOTOPE
TRANSMAT
BIOREFINERY
DURUM_WHEAT
MS2O
PO2
OAE
AFEO
OFPE
ADO
TRIPHASE
PLAPHO

**Comment by antool** [comment]
Pour l'instant, je les ai toutes mises dans la slice (et le groupe) Lovinra.
On pourra toujours modifier ensuite.

**Comment by antool** [comment]
À enlever (en attente) : OAE, AFEO, OFPE,TRIPHASE
-> slice et groupe mis à jour le 14/9/2016 : 9 ontologies

**Comment by jonquet** [comment]
Closed. On discute ca par email.
