### ISSUE TITLE
Slice/Group Wheat

### ISSUE THREAD

**Issue by antool** [agroportal/agroportal_web_ui#57]
Suivi des mises à jour pour le groupe et la slice WHEAT

**Comment by antool** [comment]
Le 13/9/2016
"CO_321", "SIO", "CO_121", "FALDO", "EFO", "VARIO", "CDAO", "PR", "TO", "XEO", "ENVO", "CL", "PATO", "NCBITAXON", "BT", "GFVO", "EO", "SNPO", "PCO", "SO", "GO", "PO", "GENO", "EDAM", "WHEATPHENOTYPE"

**Comment by jonquet** [comment]
To be assigned to Esther D-Y.

**Comment by jonquet** [comment]
Closed after discussion with Esther and regular updates.
