### ISSUE TITLE
Slice/Group Crop

### ISSUE THREAD

**Issue by antool** [agroportal/agroportal_web_ui#58]
Suivi des mises à jour pour le groupe et la slice CROP

**Comment by antool** [comment]
14/9/2016 : 15 ontologies dans la slice et le group Crop

**Comment by jonquet** [comment]
@antool et @marieALaporte Est-ce que vous pouvez écrire une mini synthese la:
-  Combien d'ontologie de cropontology.org nosu avons? Sur combien total ?
- Les raisons principales pour ne pas avoir les autres encore?
- Le planing (dans les grandes lignes)

**Comment by jonquet** [comment]
Voir  la doc: https://docs.google.com/document/d/1ISW9kyETrXxjXFsTB7LE9VQJrgD1SE6dMaJeYMiQpfU/edit#heading=h.5vknsrugm0k4
Pour mettre a jour les  slices

**Comment by jonquet** [comment]
Je ferme ce tracker "continue". Maintenant c'est documenté.
