### ISSUE TITLE
A few change in the web UI

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#59]
Sur la page "Feedback" => mettre la bonne adresse email agroportal-support@lirmm.fr

En haut a droite: créer un nouvel onglet "Info". Pour y mettre une page avec de l'information de base sur le projet. @antool Porrais tu préparer le contenu pour que Vincent n'est qu'a le mettre ?
- logo
- use cases
- partenaires
- financements
- images
- equipe (avec des petites photos de nous + sophie)
  (se baser sur ce qu'on a dans nos slides)

@antool de remplir 
https://docs.google.com/document/d/1RZc7U4pjhEzPAFJhz32oEpkAQNHdchwyusLeu-VoLsE/edit#heading=h.73u3v2qdolp9
pour implementation par @vemonet 

Sur la page "Help" => Mettre a jour la reference pour :+1: 
Clément Jonquet, Anne Toulet, Elizabeth Arnaud, Sophie Aubin, Esther Dzalé-Yeumo, Vincent Emonet, John Graybeal, Mark A. Musen, Cyril Pommier & Pierre Larmande. Reusing the NCBO BioPortal technology for agronomy to build AgroPortal, In 7th International Conference on Biomedical Ontologies, ICBO'16, Demo Session. Corvallis, Oregon, USA, August 2016. (D203), pp. 3. 
avec le lien suivant: 
http://www.lirmm.fr/~jonquet/publications/documents/Article_ICBO_2016_AgroPortal.pdf

inclure qq par un lien avers le wiki sur Git Hub

Et plus specifiquement un lien vers les release notes sur Github aussi...

**Comment by jonquet** [comment]
Sur la page d'acceuil d'AgroPortal:
- mettre les slices sous les statistics
- mettre les "latests mappings" sous les "latests notes"
- enlever le "search resources"

Utiliser la colonne de droite de la facon suivante:
- Faire un bloc "news" dans lequel  mettre une serie de news tels que décrit dans agroportal/agroportal_web_ui#62
- Faire un bloc "links" dans lequel inclure (sous forme de pictograme)
  - Le Lien vers GitHub: https://github.com/agroportal
 - Le lien vers la documentation https://github.com/agroportal/documentation/wiki
- Le lien vers le VEST/AP registry https://github.com/agroportal/documentation/wiki

**Comment by vemonet** [comment]
J'ai commencé à faire toutes ces modifications, ils manquent les infos sur le financement et les collaborateurs

**Comment by vemonet** [comment]
@antool

**Comment by antool** [comment]
Financeurs : Agence Nationale de la Recherche (ANR), Numev, IBC, Marie Curie Action (European Commission)
Organismes partenaires : 
The National Center For Biomedical Ontology (NCBO), Institut de Recherche pour le Développement (IRD), Research Data Alliance (RDA), Bioversity International, Food & Agriculture Organization (FAO), Global Open Data for Agriculture & Nutrition (Godan Action), Institut National de la Recherche Agronomique (INRA)
@jonquet tu confirmes ?

**Comment by jonquet** [comment]
Essaye de caser sur une seule page:

The AgroPortal is partly achieved within the Semantic Indexing of French biomedical Resources (SIFR – www.lirmm.fr/sifr) project that received funding from the EU H2020 research and innovation programme under the Marie Sklodowska-Curie (grant 701771) and the French National Research Agency (grant ANR-12-JS02-01001), the NUMEV Labex (grant ANR-10-LABX-20), the Computational Biology Institute of Montpellier (grant ANR-11-BINF-0002) as well as by University of Montpellier and the CNRS. We also thank the National Center for Biomedical Ontologies for help and time spent with us in deploying the AgroPortal.

**Comment by antool** [comment]
C'est fait : voir paragraphe "Description du projet AgroPortal"

**Comment by vemonet** [comment]
Clément ton texte je le met dans About non ? ("The AgroPortal is partly achieved within the Semantic Indexing of French biomedical Resources......")

**Comment by jonquet** [comment]
Oui dans l'onglet "About" ou "Info" a créer. 
Mais on va pas trop en mettre ensuite on sortira pour venir vers : le wiki de la doc. 
Il nous faut qq chose de facilement modifiable.

**Comment by vemonet** [comment]
Done
