### ISSUE TITLE
Twitter feed reader on welcome page

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#63]
Il faut in corporer (en même temps que #59 et #62 ) un lecteur de Tweets sur la page d'acceuil. Qq chose qui permette de suivre qq comptes Twitter spécifique et aussi evt un mot clé (genre "AgroPortal")

**Comment by jonquet** [comment]
Compte Twitter a suivre: 
https://twitter.com/agrohackathon
https://twitter.com/lagroportal

**Comment by vemonet** [comment]
Encore d'actualité ?

**Comment by jonquet** [comment]
Non. Pas de changement comme ça tant qu'on a pas changer d'ui
