### ISSUE TITLE
Promote the publication of data papers to describe ontologies

### ISSUE THREAD

**Issue by saubin78** [agroportal/agroportal_web_ui#64]
Publishing data papers would augment the visibility and reusability of the ontologies in AgroPortal.
A data paper for an ontology would describe e.g. its purpose, content and building.
It allows to document the ontology independently from e.g. the research project it comes from.

We would need to
- have a metadata element to link the ontology with the paper (this is useful for any paper, not only data papers, that describes the ontology). Does this exist today in AgroPortal ? I could not find it in the JFO paper
- identify (liaise with?) and recommend journals (either data journals or journals that publish data papers)
- provide templates and functionalities to pre-fill them with data available in the rdf database (?)

Sophie

**Comment by antool** [comment]
@saubin78 
We have a default property in our model which is probably suitable : omv:reference (List of bibliographic references describing the ontology and its applications) ; 
or this one, which is mapped to the precedent one : dct:bibliographicCitation (A bibliographic reference for the resource)

**Comment by jonquet** [comment]
@saubin78 est-ce que cela repond a ton besoin dans le point 1.
Pour les deux autres. Le lien ontology/data paper est de l'ordre de la perspective.

**Comment by saubin78** [comment]
To me, dct:bibliographicCitation doesn't have the same semantics as omv:reference.
omv:reference is what I want, a pointer to a publication related to the resource while dct:bibliographicCitation is describing the resource itself (like a record). See def  and comment here http://udfr.org/docs/onto/dct_bibliographicCitation.html

**Comment by jonquet** [comment]
AgroPortal currently has 1 single property to store this "reference or publication" information. 
http://data.bioontology.org/metadata/publication

In some cases, it is used to identify a page with bunch of publications
http://data.agroportal.lirmm.fr/ontologies/PR
In other, it used for one specific publication:
http://agroportal.lirmm.fr/ontologies/FALDO

We will change this in the future depending of the community agreement on the MOD project:
https://github.com/sifrproject/MOD-Ontology/
