### ISSUE TITLE
Probleme de navigation de classe avec l'ontologie CL

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#66]
@vemonet 
On a fixer qq bugs comme ca recement il me semble: TOP-MENELAS, HRDO...etc.
Est-ce que par soucis de perenisation des solutions tu pourrais commenter un peu la demarche a faire pour fixer ce genre de problème ?

**Comment by vemonet** [comment]
Problème dû à l'absence de classes "roots" : http://data.agroportal.lirmm.fr/ontologies/CL/classes/roots
Il faut que je clarifie le message d'erreur. Le problème vient du fait qu'il n'y a pas de lien vers le "top concept" de l'arbre dans l'ontologie (owl:Thing pour OWL et skos:hasTopConcept pour skos)

Mais dans le cas de CL c'est parce que c'est une ontologie au format OWL qui est ajoutée au format OBO

**Comment by jonquet** [comment]
Closed as resolved now.
