### ISSUE TITLE
Gestion des métadonnées au fil des mises à jour

### ISSUE THREAD

**Issue by antool** [agroportal/agroportal_web_ui#68]
Un exemple : j'ai changé plusieurs fois la description de GO dans AgroPortal : 
http://agroportal.lirmm.fr/ontologies/GO
mais chaque fois, celle-ci finit par être écrasée par une description inadaptée : 
Description : cvs version: $Revision: 38542 $ 
Dans cet exemple, c'est le rdfs:comment qui est extrait automatiquement du fichier et vient se substituer à la description saisie dans l'UI.
Ceci est conforme 
1) au process que nous avions décidé
2) au mapping qu'on a posé entre omv:description et rdfs:comment
À voir comment faire au mieux

**Comment by jonquet** [comment]
Oui c'est effectivement conforme a ce qu'on a mis en place. Si ils utilisent le champ "rdfs:comment" pour décrire leur version, ce n'est pas une bonne pratique. 
De notre coté, soyons sur que le champ "description" et le champs "comments" sont bien concaténés.

**Comment by antool** [comment]
Dans le fichier de GO, il n'y a pas de champ "description" mais seulement un rdfs:comment. Ce dernier est extrait automatiquement et écrase la description saisie à la main dans l'UI. Pas de concaténation dans ce cas. Et effectivement mauvaise pratique du côté des créateurs de GO

**Comment by jonquet** [comment]
Jusque la ca respecte les spécic ;)
Mais c'est un bon point en effet. On touche a un niveau de détail assez bas la.
Dans ce cas présent faut-il qu'on fasse la concatenation du rdfs:comment du fichier et, puisque il n'y a pas de champ description, le omv:description du portail ?
Je vois juste un probleme... c'est que l'omv:description du portail va contenir la concatenation avec le rdfs:comment de la version précédente... et donc on va avoir les 2 commentaires de version ajoutés au meme champ omv:description. Ce qui n'est pas forcement super car cela noie le commentaire spécifique a cette version. 

En fait ce qu'il nous faudrait ces 2 champs. Un de description et un de commentaire pacifique de version. Un moyen propre de gérer ça serait de mapper rdfs:comment a omv:notes plutôt que omv:description. Ce qui est pas forcement bête.

**Comment by antool** [comment]
Oui,c'est une bonne idée de mapper rdfs:comment à omv:notes. C'est même sûrement plus cohérent que de mapper à omv:description.
Cela règlera déjà ce problème pour GO, même si en l'occurrence il s'agit à l'origine d'une mauvaise pratique de leur côté.

**Comment by vemonet** [comment]
Fait
