### ISSUE TITLE
Bug sur homepage qui n'est pas dans le contexte

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#69]
Discuté ce matin en réunion.

**Comment by vemonet** [comment]
C'est normal
Le contexte est défini par le namespace + le nom de l'attribut.
Par exemple pour naturalLanguage c'est omv.

Dans le cas d'homepage il n'y a pas de namespace (c'est natif de BioPortal), donc le context utilise @vocab qui définit le context par défaut

**Comment by jonquet** [comment]
Comme discuté c'est ok pour publication car le nom de la propriété n'est pas le même. 

Mais pour homepage, cela ne poser pas de problème de passer a foaf pour le contexte. Sinon ce n'est pas cohérent avec le reste e.g. naturalLanguage qui était une propriété décrite dans le contexte comme un propriété omv. Idem pour eg documentation.

**Comment by jonquet** [comment]
Ok. rediscuté. A pousser en prod.
