### ISSUE TITLE
Upload automatique des ontologies CROP

### ISSUE THREAD

**Issue by antool** [agroportal/agroportal_web_ui#7]

**Comment by jonquet** [comment]
Vincent: Pour Cropontology quand on y est allé j'ai résolu le problème sur le serveur, mais ça n'a pas encore été poussé en production

**Comment by jonquet** [comment]
Ok super nouvelle. Est-ce que Marie et/ou Leo peuvent nous informer quand ce sera fait et mettre a jour l'issue.

Affecter a MArie pour ca.

**Comment by vemonet** [comment]
L'upload automatique marche très bien maintenant
