### ISSUE TITLE
Il manque doap:bug-database et doap:mailing-list dans les metadonnées

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#70]
ON ne les voit pas avec display=all

**Comment by vemonet** [comment]
C'était dû à la présence de "-" dans les propriétés, j'ai résolu ce problème (à pousser sur stage)

**Comment by jonquet** [comment]
Oui je me souvenais que le - poser un problème... mais il faut quand même qu'on puisse voir les propriétés. meme si elles sont modifiées pour ne pas avoir le -

**Comment by jonquet** [comment]
Fixed. e.g., http://data.agroportal.lirmm.fr/ontologies/PR/submissions/1?display=all
 "bugDatabase": null,
"mailingList": null,
