### ISSUE TITLE
Bug d'affichage de la propriété repository

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#71]
Est-ce que c'est un tableau cette prop ? 
Sinon bug
http://agroportal.lirmm.fr/ontologies/PR

**Comment by vemonet** [comment]
Non c'est une URL simple (et elle s'affiche en tant qu'URL simple donc je ne vois pas où ça bug)

**Comment by jonquet** [comment]
Ok. Confusion. Solved.
