### ISSUE TITLE
Bug de population des metriques dans l'apple /submission

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#72]
"numberOfClasses": null,
"numberOfIndividuals": null,
"numberOfProperties": null,
"maxDepth": null,
"maxChildCount": null,
"averageChildCount": null,
"classesWithOneChild": null,
"classesWithMoreThan25Children": null,
"classesWithNoDefinition": null,
"modificationDate": null,
"numberOfAxioms": null,

toutes les metriques devraient etre recopiées de 
http://data.agroportal.lirmm.fr/ontologies/PR/metrics

a
http://data.agroportal.lirmm.fr/ontologies/PR/latest_submission?display=all&display_links=false&display_context=true

**Comment by vemonet** [comment]
Au moment où on enregistre l'objet "metrics" on définie les metrics dans la submission.

https://github.com/sifrproject/ontologies_linked_data/blob/sifr_metadata/lib/ontologies_linked_data/models/ontology_submission.rb#L1508

Si les metrics sont calculés, ils devraient être également ajoutés dans la submission
J'ai essayé d'ajouter PR dans Stage, voir si on retrouve le même problème : 
http://stageportal.lirmm.fr/ontologies/PR

Pour les autres ça fonctionne en tout cas : 
http://data.agroportal.lirmm.fr/ontologies/TRANSMAT/latest_submission?display=all

**Comment by jonquet** [comment]
Cela doit fonctionner pour les nouvelles ontologies soumises.
http://data.agroportal.lirmm.fr/ontologies/SIO/latest_submission?display=all

Mais pas pour les anciennes soumises depuis avant le chgt:
http://data.bioportal.lirmm.fr/ontologies/MSHFRE/latest_submission?display=all

Il faudrait un patch pour fixer ce genre de bug. Peut etre juste un script externe qui consome /metrics et rempli /submission.

C'est similaire a agroportal/agroportal_web_ui#75 
A chaque fois qu'on bosse sur les metadonnées, il faut s'occuper des valeurs pour les ontologies qui étaient deja la sur agro et bio.

**Comment by jonquet** [comment]
Je ferme celui la qui est absorbé par https://github.com/agroportal/agroportal_web_ui/issues/82
