### ISSUE TITLE
hasOntologySyntax should populate automatically when OBO

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#73]
Quand le format d'une ontologie est OBO alors automatiquement  "hasOntologySyntax" doit être peupler avec "OBO" aussi.

**Comment by jonquet** [comment]
De la meme maniere si le format est UMLS alors hasOntologySyntax doit etre automatiquement affecté a Turtle

**Comment by vemonet** [comment]
OBO n'est pas dans la liste des possibilités pour hasOntologySyntax :
```ruby
{
  "http://www.w3.org/ns/formats/JSON-LD" => "JSON-LD",
  "http://www.w3.org/ns/formats/N3" => "N3",
  "http://www.w3.org/ns/formats/N-Quads" => "N-Quads",
  "http://www.w3.org/ns/formats/LD_Patch" => "LD Patch",
  "http://www.w3.org/ns/formats/microdata" => "Microdata",
  "http://www.w3.org/ns/formats/OWL_XML" => "OWL XML Serialization",
  "http://www.w3.org/ns/formats/OWL_Functional" => "OWL Functional Syntax",
  "http://www.w3.org/ns/formats/OWL_Manchester" => "OWL Manchester Syntax",
  "http://www.w3.org/ns/formats/POWDER" => "POWDER",
  "http://www.w3.org/ns/formats/POWDER-S" => "POWDER-S",
  "http://www.w3.org/ns/formats/PROV-N" => "PROV-N",
  "http://www.w3.org/ns/formats/PROV-XML" => "PROV-XML",
  "http://www.w3.org/ns/formats/RDFa" => "RDFa",
  "http://www.w3.org/ns/formats/RDF_JSON" => "RDF/JSON",
  "http://www.w3.org/ns/formats/RDF_XML" => "RDF/XML",
  "http://www.w3.org/ns/formats/RIF_XML" => "RIF XML Syntax",
  "http://www.w3.org/ns/formats/Turtle" => "Turtle",
  "http://www.w3.org/ns/formats/TriG" => "TriG"
}
```

**Comment by saubin78** [comment]
peut-être parce qu'OBO n'est pas un standard. Faut-il étendre la liste ?

**Comment by vemonet** [comment]
Pour l'instant pour hasOntologySyntax on utilise la liste des formats définie ici : http://www.w3.org/ns/formats
En soit OBO n'est pas une Syntax de RDF donc ce n'est pas étonnant de ne pas le retrouver dans cette liste (et ça ne serait pas pertinent), après on peut étendre effectivement

**Comment by jonquet** [comment]
Just asked @cmungall for the best one to use. 

Est-ce que c'est ok pour UMLS => hasOntologySyntax=Turtle

Edit Vincent: Oui

**Comment by cmungall** [comment]
http://purl.obolibrary.org/obo/oboformat/spec.html

**Comment by jonquet** [comment]
Thanks @cmungall 
@vemonet Let's use this purl URL as the URI for the OBO format.

**Comment by vemonet** [comment]
Done
