### ISSUE TITLE
downloadCsv is not automatically populated

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#75]
avec le lien du portail correspondant eg
http://data.agroportal.lirmm.fr/ontologies/PR/latest_submission?display=all&display_links=false&display_context=true

cela devrait etre 
http://data.agroportal.lirmm.fr/ontologies/PR/download?apikey=2ae6878b-a599-4cee-8224-e8efaf6f610e&download_format=csv

**Comment by jonquet** [comment]
Idem pour : dataDump et uriLookupEndpoint

**Comment by vemonet** [comment]
Ca semble fonctionner pour stageportal maintenant
http://stageportal.lirmm.fr/ontologies/PR

**Comment by jonquet** [comment]
Est-ce que cela sera rétroactif ? C'est a dire est-ce que cela va fonctionner pour les nouveaux chargements seulement ou est-ce que tu vas pouvoir peupler toutes les valeurs de toutes les ontologies déjà présentes ?
