### ISSUE TITLE
hasContributor n'est pas un array

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#78]
Faudrait que ce le soit non ? c'est ce que dit la spec.

**Comment by vemonet** [comment]
D'après la doc c'est `[String/URI]*+` ce qui signifie concaténation

**Comment by jonquet** [comment]
Oups. My mistake ;) Efefctivement cela faisait partie des propriétés qu'on avait décider de concatener pour éviter d'avoir trop de tableau a cause du probleme de la query SPARQL bas niveau.
