### ISSUE TITLE
Upload automatique des vocabulaires LovInra

### ISSUE THREAD

**Issue by antool** [agroportal/agroportal_web_ui#8]
Disposer d'une URL côté INRA pour permettre la mise à jour automatique des vocabulaires déposés sur AgroPortal

**Comment by jonquet** [comment]
Vincent: 
J'ai testé les nouveaux URLs à pull

Alors pour ceux de Stephane Dervaux le serveur ne répond pas... Donc évidemment ça marche pas
http://pfl.grignon.inra.fr/atWeb/DownloadFileServlet?type=owl&name=TRANSMAT
http://pfl.grignon.inra.fr/atWeb/DownloadFileServlet?type=owl&name=BIOREFINERY

**Comment by jonquet** [comment]
Est-ce qu'on peut demander a Stephane si il est sur GutHub pour qu'il suive avec nous cette issue?

**Comment by selios** [comment]
La plateforme pfl de grignon est de nouveau en ligne. Le test peut recommencer.

**Comment by vemonet** [comment]
L'utilisation des pull URL de TRANSMAT et BIOREFINERY ont été testés en local et marchent très bien !
A noter que j'ai également testé DURUM_WHEAT, cette ontologie est bien récupérée et parsée mais il y a des erreurs d'affichage au niveau des caractères avec accents (sûrement une histoire d'encodage)

**Comment by jonquet** [comment]
Voila les URL concernés:
http://data.stageportal.lirmm.fr/ontologies/TRANSMAT/latest_submission?include=all&display_links=false&display_context=false
http://data.stageportal.lirmm.fr/ontologies/BIOREFINERY/latest_submission?include=all&display_links=false&display_context=false

(focalisons sur ces 2 pour le moment)

**Comment by jonquet** [comment]
Pour faire le test complet, il faudrait que: 
- Stéphane fasse un changement dans l'ontologie e.g., ajouter une classe ou un label
- Attendre une nuit
- Voir le lendemain si le changement apparait dans AgroPortal

Assignée a Stephane pour ca.

**Comment by antool** [comment]
Tout est ok
