### ISSUE TITLE
Page de gestion de son compte qui plante sur AgroPortal

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#80]
http://agroportal.lirmm.fr/account 
Que sur AgroPortal 
Pas sur le SIFR BP ni sur stage. Et juste pour mon compte "jonquet" (qui est admin). Le compte "demo" fonctionne.

**Comment by vemonet** [comment]
Aucun problème quand je me connecte en tant que l'utilisateur "admin"

**Comment by jonquet** [comment]
C'est etrange. Moi aussi je peux me connecter et faire ce que je veux. Sauf aller sur la page "account" et modifier mes infos. 
Je vais voir avec le NCBO si ils ont deja eu ca.

**Comment by jonquet** [comment]
Je confirme que ce marche tjrs pas... comment peut on regenerer cette page... c'est un probleme de cache c'est sur.
Je n'ai ce probleme que sur AP

**Comment by vemonet** [comment]
Tu as essayé en navigation privée ? Si c'est un problème de cache local ça devrait le résoudre
Donc ça ne marche pas seulement pour ton compte "jonquet" ? Il faudrait que je puisse consulter les logs au moment où tu le fais

**Comment by jonquet** [comment]
Oui j'avais essayé. C'est pas du cache local. 
J'ai refais le test a 6h24 (PDT) donc 15h24 pour vous.

**Comment by vemonet** [comment]
Le problème venait d'une note de l'utilisateur "jonquet" pour laquelle il manquait des valeurs (il n'y avait que l'identifiant), ce qui faisait planter la page account. Résolu en la supprimant
