### ISSUE TITLE
Supprimer la valeur d'une métadonnée via l'API

### ISSUE THREAD

**Issue by antool** [agroportal/agroportal_web_ui#81]
Comment supprimer la valeur d'une métadonnées pour une ontologie donnée ?
Le cas se pose pour un champ de métadonnée rempli et que l'on voudrait supprimer sans rien mettre à la place (sinon il suffit de refaire un "patch" avec la nouvelle valeur).

**Comment by jonquet** [comment]
Il faut juste faire HTTP PATCH avec une valeur vide.

**Comment by antool** [comment]
Dans le http patch : la valeur "vide" n'a aucun effet (ne supprime ni ne remplace la valeur antérieure), la valeur "espace" n'est pas acceptée. On peut gruger avec la valeur explicite "null" mais le résultat n'est pas très joli puisque la propriété de métadonnée est toujours affichée avec la valeur "local:null"
Donc, la question reste ouverte : comment supprimer une métadonnée que l'on aurait remplie mais que l'on ne souhaite plus voir affichée ?

**Comment by vemonet** [comment]
Ca marche pour le texte et les arrays (en mettant un array vide : [] )

Ca ne marche pas seulement pour les URI simple (quand on donne un nil ou un "" ) 
Je fouille au fin fond de ontologies_api et ontologies_linked_data pour trouver pourquoi ça ne fonctionne pas 

Pour l'instant je suis sur des trucs du genre "# TODO: Remove this awful hack when obj.class.model_settings[:range][attribute] contains RDF::IRI class" ...

**Comment by antool** [comment]
Typiquement ça ne marche pas pour logo avec comme valeur une url

**Comment by vemonet** [comment]
Oui je sais, j'ai résolu le problème et poussé en prod

**Comment by antool** [comment]
Du coup, qu'est-ce qui est pris en compte par l'UI maintenant ?
Imaginons que je veuille supprimer la métadonnée "Logo" par exemple

**Comment by vemonet** [comment]
Tu ne mets rien dedans

**Comment by antool** [comment]
C'est parfait :-)
