### ISSUE TITLE
Relaoder toutes les ontologies de SIFR et Agro une fois les peuplement de metadonnées automatique faits

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#82]
Par exemple: 
https://github.com/agroportal/agroportal_web_ui/issues/75
https://github.com/agroportal/agroportal_web_ui/issues/76
https://github.com/agroportal/agroportal_web_ui/issues/74
etc.

**Comment by jonquet** [comment]
Attention, j'ai constaté des problèmes avec homepage, documentation et publication. Ces champs n'ont pas été affectés via l'UI. Je refais des essais pour y voir plus clair. 
Bien pensé a faire une sauvegarde du JSON avant de reloader les ontologies... au cas ou la metadonnées ne soit pas bien transférée aux nouvelles versions.
http://data.agroportal.lirmm.fr/submissions?display=all

**Comment by jonquet** [comment]
Cela ne sera pas necessaire ni sur SIFR (fait par @jonquet) ni pour AgroPortal (cf. https://github.com/agroportal/agroportal_web_ui/issues/47)

**Comment by jonquet** [comment]
En fait je réouvre et m'assigne ca a moi meme pour le faire. Il y a plein de truc automatique qui seront fait alors. 
E.g., 
https://github.com/agroportal/agroportal_web_ui/issues/84

**Comment by vemonet** [comment]
To reprocess ontologies (extracting and generating metadata values):

You need to be connected as root

```shell
# It's important to be in this precise repertory when running the script
cd /srv/ncbo/ncbo_cron

# To reprocess a particular ontology:
bin/ncbo_ontology_process -o ACRONYM

# To reprocess all ontologies:
bin/ncbo_ontology_process -a
```

**Comment by jonquet** [comment]
OK script testé ce matin. Avec access spécifique mis en place. 
@antool On a décidé de pas relancer tout automatiquement mais plutot de reprocesser les ontologies au cas par cas.
