### ISSUE TITLE
Métadonnées non extraites dans AEO

### ISSUE THREAD

**Issue by antool** [agroportal/agroportal_web_ui#83]
Quelques métadonnées sont renseignées dans le fichier owl [http://agroportal.lirmm.fr/ontologies/AEO](url) mais ne sont pas extraites par AgroPortal : par exemple, dc:creator, dc:contributor, rdfs:comment, dc:rights
Probablement en raison d'une syntaxe assez particulère mais qui cependant est bien "lue" dans Protégé 5.1. (voir le rendu dans la capture d'écran ci-dessous)

![aeo-protege1](https://cloud.githubusercontent.com/assets/16287223/23400924/ff685f52-fda5-11e6-886d-c25139679839.png)

**Comment by jonquet** [comment]
Regardé ce matin. A suivre avec un autre example qui marche. Il est pas impossible que cela vienne du format OWL/XML... ou du fait que ce soit des annotations properties.

**Comment by vemonet** [comment]
```xml
<Annotation>
  <AnnotationProperty IRI="http://purl.org/dc/elements/1.1/contributor"/>
  <Literal datatypeIRI="http://www.w3.org/1999/02/22-rdf-syntax-ns#PlainLiteral">Alexandre MAIRIN, Jonathan MINEAU, Isabelle Nembrot, Aunur-Rofiq MULJARTO</Literal>
</Annotation>
```

Voir où se retrouvent ses propriétés dans le 4store (est-ce que ces propriétés sont bien rattachées à l'objet Ontology ?)

**Comment by vemonet** [comment]
Test en l'uploadant sur stage : http://stageportal.lirmm.fr/ontologies/AEO
J'ai testé direct dans le SPARQL endpoint normalement ça devrait être extrait sans problème

http://sparql.agroportal.lirmm.fr/test/
```sql
PREFIX omv: <http://omv.ontoware.org/2005/05/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?extractedObject ?omvname ?omvfirstname ?omvlastname ?rdfslabel
FROM <http://data.bioontology.org/ontologies/AEO/submissions/1>
WHERE {
  <http://www.mistea.supagro.inra.fr/ontologies/2015/aeo> <http://purl.org/dc/elements/1.1/contributor> ?extractedObject .
  OPTIONAL { ?extractedObject omv:name ?omvname } .
  OPTIONAL { ?extractedObject omv:firstName ?omvfirstname } .
  OPTIONAL { ?extractedObject omv:lastName ?omvlastname } .
  OPTIONAL { ?extractedObject rdfs:label ?rdfslabel } .
}
```

**Comment by vemonet** [comment]
Corrigé, sera poussé à la prochaine mise à jour
