### ISSUE TITLE
Propriétés de metadata manquantes (et non peuplées automatiquement)

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#84]
schema:url
void:propertyPartition
void:classPartition
void:rootResource

Elle ne sont pas dans le listing ?
http://data.agroportal.lirmm.fr/ontologies/PR/submissions/1?display=all
 Ces 4 devaient être automatiquement générées en tant que valeur des lines
ui
properties
classes
roots

Soit pour PR: 
url: http://agroportal.lirmm.fr/ontologies/PR
properties: http://data.agroportal.lirmm.fr/ontologies/PR/properties
classes: http://data.agroportal.lirmm.fr/ontologies/PR/classes
roots: http://data.agroportal.lirmm.fr/ontologies/PR/classes/root

**Comment by vemonet** [comment]
Prévu pour la release 2

**Comment by jonquet** [comment]
Oui ceci est une erreur. On fera ces propriétés (en rouge dans le GDoc) dans une prochaine release si on abandonne la backward compatibility avec le NCBO BioPortal.
