### ISSUE TITLE
Dump properties mal peuplées

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#85]
Exemple avec SIO: 

Pour le moment dataDump est peuplée avec 
 "http://data.agroportal.lirmm.fr/ontologies/SIO/download"
(c'est fait automatiquement...)

Il faudrait en fait que:
dataDump:http://data.agroportal.lirmm.fr/ontologies/SIO/download?download_format=rdf
et 
csvDump:http://data.agroportal.lirmm.fr/ontologies/SIO/download?download_format=csv

**Comment by vemonet** [comment]
Déclaration des attr Dump: https://github.com/sifrproject/ontologies_linked_data/blob/sifr_metadata/lib/ontologies_linked_data/models/ontology_submission.rb#L191

Peuplement auto : https://github.com/sifrproject/ontologies_linked_data/blob/sifr_metadata/lib/ontologies_linked_data/models/ontology_submission.rb#L790

Exactement le même type d'attributs et la même façon de les peupler. Mais csvDump ne se peuple pas, à investiguer

**Comment by antool** [comment]
Problème aussi avec les propriétés peuplées automatiquement qui commencent par data.agroportal… le lien pointe sur le json mais cela ne s'affiche pas car il est demandé une API Key Exemple pour "open Search Description" : http://data.agroportal.lirmm.fr/search?ontologies=ENVO
ou "uri Lookup Endpoint" : http://data.agroportal.lirmm.fr/search?ontologies=ENVO

**Comment by jonquet** [comment]
Je pense que c'est pas un problème pour les apikey absentes. La données est la. Cela veut pas dire qu'en un lien on peut l'obtenir. L'idée de ces métadonnées est plus d'être remplies pour éduquer/montrer que pour leur valeurs par défaut réelle.

**Comment by antool** [comment]
Tu as probablement raison mais il n'en demeure pas moins qu'un utilisateur lambda se dira que le lien ne fonctionne pas.
Dans ce cas, on peut proposer un lien plus générique du type : http://agroportal.lirmm.fr/search

**Comment by jonquet** [comment]
Oui mais dans l'UI le lien vers "Search" dans AgroPortal il est deja dans la barre principale. 
Mon opinion est que de toute facon ce champ la de métadonnée sera simplement représenté par un petit bouton genre "API Search" et que au contraire, cela indiquera aux gens ou chercher en se limitant a cette ontologie (information qui sinon devrait etre trouvé sur un autre site (data.../doc) apres avoir lu 3 pages de doc. 

Cela dit pour uri Lookup Endpoint il faut etre plus precis et mettre l'URL suivante @vemonet  :

http://data.agroportal.lirmm.fr/search?ontologies=NCBITAXON&require_exact_match=true&q=

e.g.,
http://data.agroportal.lirmm.fr/search?ontologies=NCBITAXON&require_exact_match=true&q=http://purl.bioontology.org/ontology/NCBITAXON/60277

**Comment by jonquet** [comment]
Une nouvelle ontologie uploadée ce WE sur le SIFR BP. Les 3 propriétés discutées ici ne sont pas peuplées comme il faut. @vemonet on en est ou ?

**Comment by vemonet** [comment]
Sur la VM ça marche. On fait le point avec Anne cet aprem
