### ISSUE TITLE
Vérifier les modifications dans les ontologies chaque semaine au lieu de chaque jour ?

### ISSUE THREAD

**Issue by vemonet** [agroportal/agroportal_web_ui#87]
Pour le moment on vérifie chaque soir s'il y a eu une modification dans les ontologies. Pour certaines ontologies tel que transmat et biorefinery ça provoque un upload d'une nouvelle soumission chaque jour

Ne serait-il pas plus intéressant de faire ça chaque semaine ou 2 fois par semaine ?

**Comment by jonquet** [comment]
Ok apres discussion, seulement TRANSMAT, BIOREFINERY et GO nous pose vraiment problème car elles sont mise a jour trop souvent sur AgroPortal. On regarde si on peut faire un traitement particulier pour ces 3 ontologies. 

En outre, pour ces 3 ontologies, dans les archives, on garde qu'un fichier sur 10.

**Comment by vemonet** [comment]
Only for TRANSMAT, BIOREFINERY and GO. See https://github.com/agroportal/agroportal_web_ui/issues/90
