### ISSUE TITLE
Automatically synchronize slices to groups

### ISSUE THREAD

**Issue by vemonet** [agroportal/agroportal_web_ui#89]
Fix that :
https://docs.google.com/document/d/1ISW9kyETrXxjXFsTB7LE9VQJrgD1SE6dMaJeYMiQpfU/edit#heading=h.35efuvm967ip

Si le bug à la création de la slice est toujours présent, on pourrait faire en sorte que ça ne marche que pour les slices déjà existantes.

**Comment by jonquet** [comment]
En fait ce qui se passe c'est que si la slice existe pas (mais le groupe  oui) ca crée.

**Comment by vemonet** [comment]
Fixed. We can now synchronize slices to groups calling the URL `/slices/synchronize_groups` :
http://data.agroportal.lirmm.fr/slices/synchronize_groups
We need to use the API Key of an admin account to make it work.

It will work on agroportal and SIFR BioPortal next time we will update everything
