### ISSUE TITLE
Avoid auto pull of frequently updated ontologies

### ISSUE THREAD

**Issue by vemonet** [agroportal/agroportal_web_ui#90]
3 ontologies are modified really frequently (almost daily) : TRANSMAT, BIOREFINERY and GO

Avoid pulling them too often (especially GO that is really heavy)

**Comment by jonquet** [comment]
Yes. We need to find a way to customize the automatic updates "per ontology".
3 of our ontologies are being updated everynight and create a lot of disk space usage. We would like, for these 3 ontologies only to cutomize the update process (using pullURL) to once a week.

Asking @mdorf and @jvendetti if they ahve already done something like that ?

**Comment by vemonet** [comment]
Now pull once every week on monday at 23:00. The list of ontologies concerned and the cron schedule can be changed in NcboCron params in config file
