### ISSUE TITLE
Create a new ontology group/slice for the AgBioData working group

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#95]

**Comment by jonquet** [comment]
Information to create the group: 
AGBIODATA
http://agbiodata.agroportal.lirmm.fr
Consortium of Agricultural Biological Databases
AgBioData is a consortium of agricultural biological databases which strive to identify common goals relating to data set acquisition, display, user retrieval and manipulation; data, software and hardware standards, and database best practices. 
GO, TO, PO, EO, PATO, ENVO, ChEBI, CO, CO_715, ECO, SOY, CL, AGRO, EFO, PCO, PR, SO, VARIO, Uberon, VT, LPT, ATOL, LBO, CMO, MI, ECO, FALDO, FLOPO, TGMA, TADS, MIRO, IDOMAL, IDODEN, , VBCV, IDO, CABT, NALT, AGROVOC, BIOREFINERY
Sook Jung
More info here: https://www.agbiodata.org/

**Comment by jonquet** [comment]
Group created. And ontologies added manually. Just need to add the CO ones.

**Comment by jonquet** [comment]
Ok done. Assign to Vincent to create the slice.

**Comment by vemonet** [comment]
Pour mettre à jour les slices en fonction des groupes il suffit de faire http://data.agroportal.lirmm.fr/slices/synchronize_groups (c'est fait)
