### ISSUE TITLE
Bug with Agrovoc search

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#96]
Search for "Arabidopsis" this is not find in Agrovoc, where as the Annotator catch a concept

**Comment by vemonet** [comment]
Reindexing fait sur le core2. Mais ca ne semble pas avoir résolu le problème...
Reindexing lancé sur core1

**Comment by vemonet** [comment]
Il semblerait que ce soit inhérent aux ontologies au format SKOS.
C'est le même problème pour NALT. Sûrement que l'indexation se fait sur les owl:Class (et non pas les skos:Concepts qui sont considérés comme des individuals)

**Comment by vemonet** [comment]
Vu avec Misha : il y avait un bug dans l'indexation des ontologies SKOS (seulement la première page était indexée). Il avait déjà fait un fix pour NLMVS, il l'a étendu pour toutes les ontologies SKOS
https://github.com/ncbo/ontologies_linked_data/blob/staging/lib/ontologies_linked_data/models/ontology_submission.rb#L1112

Par contre ce ne sera poussé sur Master qu'en Juin. Donc il vaut mieux puller la dernière version de staging pour ontologies_linked_data (une fois que le fix aura été étendu)

```ruby
# Sinon, juste à remplacer
cls_count = (self.ontology.acronym === "NLMVS") ? -1 : class_count(logger)
# par
self.bring(:hasOntologyLanguage) unless self.loaded_attributes.include?(:hasOntologyLanguage)
```

**Comment by vemonet** [comment]
In production, fixed.
