### ISSUE TITLE
Access class JSON point error

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#97]
Go to:
http://agroportal.lirmm.fr/ontologies/AGROVOC?p=classes&conceptid=http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_33291

Click on the new "Access Class JSON" button 
You will ned here:
http://data.agroportal.lirmm.fr/ontologies/AGROVOC/classes/

Rather than here:
http://data.agroportal.lirmm.fr/ontologies/AGROVOC/classes/http%3A%2F%2Faims.fao.org%2Faos%2Fagrovoc%2Fc_33291?display_links=false&display_context=false&display=all

**Comment by vemonet** [comment]
It is normal.
When the page just load I don't get the auto selected class. So we link to all classes. When a class is clicked we get the selected class, then we generate the URI according to this class
