### ISSUE TITLE
Upload of NALT

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#99]
Open to follow up on #35.

NALT created on AgroPortal today and test of uploading v2015

**Comment by jonquet** [comment]
Same issue observed on NALT than on NALT-2016. 
"NoMethodError: undefined method `id=' for nil:NilClass" during parsing.
Impossible to get a clue about which class generates a nil.
@vemonet can you have a look?

However /annotator and /search works.

**Comment by antool** [comment]
24 April 2017: New test with modification of the topConcept in each of the 17 conceptScheme. It seems to work !

**Comment by jonquet** [comment]
Great. Browsing works, /search does not work yet but /annotator does

**Comment by antool** [comment]
Done for the 3 latest versions: 2015, 2016, 2017.
What to change in the original NALT file to do it working in AgroPortal?
The skos:hasTopConcept are not well defined. For each of the 17 skos:conceptScheme, define one and only one skos:hasTopConcept (which is in fact parent of all the false "top concepts" defined in the original file).
To do that, just change the part `<!-- Concept schemes -->` at the end of the original file by this one: 
[conceptScheme-nalt.rdf.zip](https://github.com/agroportal/agroportal_web_ui/files/958760/conceptScheme-nalt.rdf.zip)
To be verified for each new version of NALT.

**Comment by jonquet** [comment]
Great 👍🏼 congratulations @antool !

Is search service ok now that the parsing is done properly?
We need to contact NAL for them to claim it.

**Comment by antool** [comment]
For the record, here are the contacts
Responsible: Sujata Suri, Sujata.Suri@ARS.USDA.GOV
Responsible (informatic branch): Lori Finch, lori.finch@ars.usda.gov
